import { expect, test } from '@playwright/test'

test('zoom follows the player and four music tracks cycle with independent volume', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await expect.poll(() => page.evaluate(() => window.__CHEMSITE_DEBUG__?.getSnapshot().sceneReady)).toBe(true)
  await page.getByRole('button', { name: /Карьерный режим/ }).click()
  await page.getByRole('button', { name: 'Начать уровень' }).click()
  const music = page.getByTestId('background-music')
  await expect.poll(() => music.evaluate((node) => (node as HTMLAudioElement).currentTime)).toBeGreaterThan(0)
  for (let i = 0; i < 4; i++) {
    await expect(music).toHaveAttribute('src', `/assets/audio/lofi-${i + 1}.mp3`)
    await music.dispatchEvent('ended')
  }
  await expect(music).toHaveAttribute('src', '/assets/audio/lofi-1.mp3')
  await page.mouse.move(720, 450)
  await page.mouse.wheel(0, -200)
  await expect(page.getByRole('button', { name: '135%' })).toBeVisible()
  await page.getByTitle('Сбросить масштаб. Колесо мыши — приближение').click()
  for (let i = 0; i < 9; i++) await page.getByRole('button', { name: 'Приблизить камеру' }).click()
  await expect(page.getByRole('button', { name: '280%' })).toBeVisible()
  await page.waitForTimeout(1200)
  await page.screenshot({ path: 'artifacts/playtest/polish-character-zoom.png' })
  await page.keyboard.down('KeyW')
  await page.waitForTimeout(500)
  await page.keyboard.up('KeyW')
  await page.keyboard.press('Escape')
  await page.getByRole('slider', { name: 'Громкость музыки' }).fill('0')
  await expect.poll(() => music.evaluate((node) => (node as HTMLAudioElement).paused)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '280%' }).click()
  await page.waitForTimeout(1000)
  await page.screenshot({ path: 'artifacts/playtest/polish-site.png' })
  await page.waitForTimeout(1200)
  await page.reload()
  await expect.poll(() => page.evaluate(() => window.__CHEMSITE_DEBUG__?.getSnapshot().sceneReady)).toBe(true)
  await expect.poll(() => music.evaluate((node) => (node as HTMLAudioElement).volume)).toBe(0)
  expect(errors).toEqual([])
})
