import type { TaskDefinition } from '../types'

type LevelOneTaskInput = Omit<
  TaskDefinition,
  'id' | 'level' | 'points' | 'procedural' | 'reviewStatus'
>

const makeTask = (number: number, definition: LevelOneTaskInput): TaskDefinition => ({
  ...definition,
  id: `L1-${String(number).padStart(3, '0')}`,
  level: 1,
  points: 100,
  procedural: false,
  reviewStatus: 'verified',
})

const classOptions = ['кислота', 'основание', 'соль', 'оксид']
const oxideOptions = ['основный оксид', 'кислотный оксид', 'амфотерный оксид', 'несолеобразующий оксид']

export const level1Tasks: readonly TaskDefinition[] = [
  makeTask(1, {
    topic: 'Номенклатура', subtopic: 'Соли', difficulty: 1,
    station: 'substance-storage', interactionType: 'substance-card',
    prompt: 'Назови вещество BaSO₄.', correctAnswer: 'сульфат бария',
    acceptedAnswers: ['barium sulfate'],
    options: ['сульфат бария', 'сульфит бария', 'карбонат бария', 'сульфид бария'],
    explanation: 'BaSO₄ состоит из катиона Ba²⁺ и сульфат-иона SO₄²⁻.',
    rule: 'SO₄²⁻ называется сульфатом.', example: 'Na₂SO₄ — сульфат натрия.',
    hint: 'Определи название иона SO₄²⁻.', tags: ['salt', 'sulfate', 'barium'],
    parameters: { compound: 'BaSO4' },
  }),
  makeTask(2, {
    topic: 'Номенклатура', subtopic: 'Сульфиты и сульфаты', difficulty: 1,
    station: 'substance-storage', interactionType: 'substance-card',
    prompt: 'Назови вещество BaSO₃.', correctAnswer: 'сульфит бария',
    options: ['сульфит бария', 'сульфат бария', 'сульфид бария', 'карбонат бария'],
    explanation: 'BaSO₃ содержит сульфит-ион SO₃²⁻.',
    rule: 'SO₃²⁻ — сульфит, SO₄²⁻ — сульфат.', example: 'Na₂SO₃ — сульфит натрия.',
    hint: 'У сульфит-иона три атома кислорода.', tags: ['salt', 'sulfite', 'barium'],
    parameters: { compound: 'BaSO3' },
  }),
  makeTask(3, {
    topic: 'Номенклатура', subtopic: 'Кислые соли', difficulty: 1,
    station: 'substance-storage', interactionType: 'substance-card',
    prompt: 'Назови вещество NaHCO₃.', correctAnswer: 'гидрокарбонат натрия',
    acceptedAnswers: ['бикарбонат натрия', 'sodium bicarbonate'],
    options: ['гидрокарбонат натрия', 'карбонат натрия', 'гидроксид натрия', 'нитрат натрия'],
    explanation: 'NaHCO₃ содержит катион Na⁺ и гидрокарбонат-ион HCO₃⁻.',
    rule: 'HCO₃⁻ называется гидрокарбонатом.', example: 'Ca(HCO₃)₂ — гидрокарбонат кальция.',
    hint: 'В анионе HCO₃⁻ сохраняется атом водорода.', tags: ['salt', 'hydrogen-carbonate', 'sodium'],
    parameters: { compound: 'NaHCO3' },
  }),
  makeTask(4, {
    topic: 'Номенклатура', subtopic: 'Соли', difficulty: 1,
    station: 'substance-storage', interactionType: 'substance-card',
    prompt: 'Назови вещество CaCO₃.', correctAnswer: 'карбонат кальция',
    options: ['карбонат кальция', 'гидрокарбонат кальция', 'оксид кальция', 'сульфат кальция'],
    explanation: 'CaCO₃ состоит из Ca²⁺ и карбонат-иона CO₃²⁻.',
    rule: 'CO₃²⁻ называется карбонатом.', example: 'CaCO₃ — основной компонент известняка.',
    hint: 'Распознай карбонат-ион CO₃²⁻.', tags: ['salt', 'carbonate', 'calcium', 'construction'],
    constructionContext: 'Карбонат кальция входит в состав известняка.', parameters: { compound: 'CaCO3' },
  }),
  makeTask(5, {
    topic: 'Номенклатура', subtopic: 'Соли переходных металлов', difficulty: 2,
    station: 'substance-storage', interactionType: 'substance-card',
    prompt: 'Назови вещество FeCl₃.', correctAnswer: 'хлорид железа(III)',
    acceptedAnswers: ['хлорид железа 3', 'хлорид железа (iii)'],
    options: ['хлорид железа(III)', 'хлорид железа(II)', 'хлорат железа(III)', 'хлорид алюминия'],
    explanation: 'Три иона Cl⁻ требуют катион Fe³⁺, поэтому железо имеет степень окисления +3.',
    rule: 'Для металлов с переменной степенью окисления её указывают римской цифрой.',
    example: 'FeCl₂ — хлорид железа(II).', hint: 'Суммарный заряд трёх Cl⁻ равен −3.',
    tags: ['salt', 'chloride', 'iron', 'oxidation-state'], parameters: { compound: 'FeCl3' },
  }),
  makeTask(6, {
    topic: 'Номенклатура', subtopic: 'Соли переходных металлов', difficulty: 2,
    station: 'substance-storage', interactionType: 'substance-card',
    prompt: 'Назови вещество CuSO₄.', correctAnswer: 'сульфат меди(II)',
    acceptedAnswers: ['сульфат меди 2', 'сульфат меди (ii)'],
    options: ['сульфат меди(II)', 'сульфит меди(II)', 'сульфат меди(I)', 'карбонат меди(II)'],
    explanation: 'Сульфат-ион имеет заряд −2, поэтому катион меди здесь Cu²⁺.',
    rule: 'Степень окисления меди указывают в названии соли.', example: 'CuCl₂ — хлорид меди(II).',
    hint: 'Уравновесь заряд SO₄²⁻ зарядом меди.', tags: ['salt', 'sulfate', 'copper'],
    parameters: { compound: 'CuSO4' },
  }),
  makeTask(7, {
    topic: 'Химические формулы', subtopic: 'Баланс зарядов', difficulty: 1,
    station: 'formula-board', interactionType: 'formula-builder',
    prompt: 'Собери формулу карбоната кальция из Ca²⁺ и CO₃²⁻.', correctAnswer: 'CaCO3',
    explanation: 'Заряды +2 и −2 компенсируются в отношении 1:1.',
    rule: 'Суммарный заряд нейтральной формульной единицы равен нулю.', example: 'Mg²⁺ + CO₃²⁻ → MgCO₃.',
    hint: 'Оба иона имеют одинаковый по модулю заряд.', tags: ['formula', 'carbonate', 'calcium'],
    parameters: { formulaTokens: ['Ca', 'CO₃'], compound: 'CaCO3' },
  }),
  makeTask(8, {
    topic: 'Химические формулы', subtopic: 'Баланс зарядов', difficulty: 2,
    station: 'formula-board', interactionType: 'formula-builder',
    prompt: 'Собери формулу сульфата алюминия из Al³⁺ и SO₄²⁻.', correctAnswer: 'Al2(SO4)3',
    explanation: 'Наименьшее общее кратное зарядов 3 и 2 равно 6: нужны 2 Al³⁺ и 3 SO₄²⁻.',
    rule: 'Многоатомный ион берут в скобки, когда его индекс больше единицы.', example: 'Al₂(SO₄)₃.',
    hint: 'Уравняй заряды до +6 и −6.', tags: ['formula', 'sulfate', 'aluminium'],
    parameters: { formulaTokens: ['Al', '₂', '(', 'SO₄', ')', '₃'], compound: 'Al2(SO4)3' },
  }),
  makeTask(9, {
    topic: 'Химические формулы', subtopic: 'Соли переходных металлов', difficulty: 2,
    station: 'formula-board', interactionType: 'formula-builder',
    prompt: 'Напиши формулу нитрата железа(III).', correctAnswer: 'Fe(NO3)3',
    explanation: 'Fe³⁺ требует три нитрат-иона NO₃⁻.',
    rule: 'Три одинаковых многоатомных иона записывают со скобками.', example: 'Al(NO₃)₃ — нитрат алюминия.',
    hint: 'Сочетай Fe³⁺ с тремя NO₃⁻.', tags: ['formula', 'nitrate', 'iron'],
    parameters: { formulaTokens: ['Fe', '(', 'NO₃', ')', '₃'], compound: 'Fe(NO3)3' },
  }),
  makeTask(10, {
    topic: 'Химические формулы', subtopic: 'Кислые соли', difficulty: 2,
    station: 'formula-board', interactionType: 'formula-builder',
    prompt: 'Напиши формулу гидрокарбоната бария.', correctAnswer: 'Ba(HCO3)2',
    explanation: 'Ba²⁺ уравновешивают два гидрокарбонат-иона HCO₃⁻.',
    rule: 'При нескольких многоатомных ионах используют скобки.', example: 'Ca(HCO₃)₂.',
    hint: 'К одному Ba²⁺ нужны два однозарядных аниона.', tags: ['formula', 'hydrogen-carbonate', 'barium'],
    parameters: { formulaTokens: ['Ba', '(', 'HCO₃', ')', '₂'], compound: 'Ba(HCO3)2' },
  }),
  makeTask(11, {
    topic: 'Химические формулы', subtopic: 'Исправление формул', difficulty: 1,
    station: 'formula-board', interactionType: 'formula-builder',
    prompt: 'На доске написано CaCl. Исправь формулу хлорида кальция.', correctAnswer: 'CaCl2',
    explanation: 'Катиону Ca²⁺ нужны два аниона Cl⁻.', rule: 'Индексы отражают наименьшее целое соотношение ионов.',
    example: 'MgCl₂.', hint: 'Компенсируй заряд +2 двумя хлорид-ионами.',
    tags: ['formula', 'chloride', 'calcium'], parameters: { formulaTokens: ['Ca', 'Cl', '₂'], compound: 'CaCl2' },
  }),
  makeTask(12, {
    topic: 'Химические формулы', subtopic: 'Исправление формул', difficulty: 2,
    station: 'formula-board', interactionType: 'formula-builder',
    prompt: 'На доске написано AlSO₄. Исправь формулу сульфата алюминия.', correctAnswer: 'Al2(SO4)3',
    explanation: 'Два Al³⁺ и три SO₄²⁻ дают нейтральную формульную единицу.',
    rule: 'Сумма зарядов катионов и анионов должна равняться нулю.', example: 'Al₂(SO₄)₃.',
    hint: 'Наименьшее общее кратное 3 и 2 равно 6.', tags: ['formula', 'sulfate', 'aluminium'],
    parameters: { formulaTokens: ['Al', '₂', '(', 'SO₄', ')', '₃'], compound: 'Al2(SO4)3' },
  }),
  makeTask(13, {
    topic: 'Химические формулы', subtopic: 'Исправление формул', difficulty: 1,
    station: 'formula-board', interactionType: 'formula-builder',
    prompt: 'На доске написано MgOH₂. Исправь формулу гидроксида магния.', correctAnswer: 'Mg(OH)2',
    explanation: 'Две группы OH⁻ записывают в скобках: Mg(OH)₂.',
    rule: 'Скобки сохраняют целостность многоатомного иона.', example: 'Ca(OH)₂.',
    hint: 'Индекс 2 относится ко всей группе OH.', tags: ['formula', 'hydroxide', 'magnesium'],
    parameters: { formulaTokens: ['Mg', '(', 'OH', ')', '₂'], compound: 'Mg(OH)2' },
  }),
  makeTask(14, {
    topic: 'Классы веществ', subtopic: 'Кислоты', difficulty: 1,
    station: 'substance-storage', interactionType: 'classification',
    prompt: 'К какому классу относится H₂SO₄?', correctAnswer: 'кислота', options: classOptions,
    explanation: 'H₂SO₄ — серная кислота.', rule: 'Кислоты в растворе образуют катионы H⁺ и анионы кислотного остатка.',
    example: 'HCl — соляная кислота.', hint: 'Формула начинается с атомов водорода.', tags: ['classification', 'acid'],
    parameters: { compound: 'H2SO4' },
  }),
  makeTask(15, {
    topic: 'Классы веществ', subtopic: 'Основания', difficulty: 1,
    station: 'substance-storage', interactionType: 'classification',
    prompt: 'К какому классу относится NaOH?', correctAnswer: 'основание',
    acceptedAnswers: ['щелочь', 'основание, щелочь'], options: classOptions,
    explanation: 'NaOH — растворимое основание, то есть щёлочь.', rule: 'Основания содержат катион металла и гидроксид-ионы.',
    example: 'KOH — щёлочь.', hint: 'Найди группу OH.', tags: ['classification', 'base', 'alkali'],
    parameters: { compound: 'NaOH' },
  }),
  makeTask(16, {
    topic: 'Классы веществ', subtopic: 'Основания', difficulty: 1,
    station: 'substance-storage', interactionType: 'classification',
    prompt: 'К какому классу относится Cu(OH)₂?', correctAnswer: 'основание',
    acceptedAnswers: ['малорастворимый гидроксид', 'основание, малорастворимый гидроксид'], options: classOptions,
    explanation: 'Cu(OH)₂ — малорастворимое основание.', rule: 'Гидроксиды металлов обычно относят к основаниям.',
    example: 'Fe(OH)₃ — малорастворимый гидроксид.', hint: 'Формула содержит металл и группы OH.',
    tags: ['classification', 'base', 'copper'], parameters: { compound: 'Cu(OH)2' },
  }),
  makeTask(17, {
    topic: 'Классы веществ', subtopic: 'Амфотерные гидроксиды', difficulty: 2,
    station: 'substance-storage', interactionType: 'classification',
    prompt: 'К какому классу относится Al(OH)₃?', correctAnswer: 'амфотерный гидроксид',
    options: ['щелочь', 'амфотерный гидроксид', 'кислота', 'соль'],
    explanation: 'Al(OH)₃ проявляет кислотные и основные свойства.', rule: 'Амфотерные гидроксиды реагируют и с кислотами, и со щелочами.',
    example: 'Zn(OH)₂ также амфотерен.', hint: 'Гидроксид алюминия проявляет двойственный характер.',
    tags: ['classification', 'amphoteric', 'aluminium'], parameters: { compound: 'Al(OH)3' },
  }),
  makeTask(18, {
    topic: 'Классы веществ', subtopic: 'Оксиды', difficulty: 1,
    station: 'substance-storage', interactionType: 'classification',
    prompt: 'К какому классу относится CaO?', correctAnswer: 'основный оксид', options: oxideOptions,
    explanation: 'CaO — основный оксид активного металла.', rule: 'Основные оксиды реагируют с кислотами с образованием соли и воды.',
    example: 'CaO + 2HCl → CaCl₂ + H₂O.', hint: 'Кальций — активный металл.', tags: ['classification', 'oxide', 'calcium'],
    constructionContext: 'CaO используется в известковом цикле.', parameters: { compound: 'CaO' },
  }),
  makeTask(19, {
    topic: 'Классы веществ', subtopic: 'Оксиды', difficulty: 1,
    station: 'substance-storage', interactionType: 'classification',
    prompt: 'К какому классу относится SO₃?', correctAnswer: 'кислотный оксид', options: oxideOptions,
    explanation: 'SO₃ — кислотный оксид; с водой он образует H₂SO₄.', rule: 'Многие оксиды неметаллов являются кислотными.',
    example: 'SO₃ + H₂O → H₂SO₄.', hint: 'Сера в высокой степени окисления образует кислотный оксид.',
    tags: ['classification', 'oxide', 'sulfur'], parameters: { compound: 'SO3' },
  }),
  makeTask(20, {
    topic: 'Классы веществ', subtopic: 'Оксиды', difficulty: 2,
    station: 'substance-storage', interactionType: 'classification',
    prompt: 'К какому классу относится Al₂O₃?', correctAnswer: 'амфотерный оксид', options: oxideOptions,
    explanation: 'Al₂O₃ реагирует и с кислотами, и со щелочами.', rule: 'Амфотерные оксиды проявляют кислотные и основные свойства.',
    example: 'ZnO — амфотерный оксид.', hint: 'Оксид алюминия обладает двойственными свойствами.',
    tags: ['classification', 'oxide', 'amphoteric', 'aluminium'], parameters: { compound: 'Al2O3' },
  }),
  makeTask(21, {
    topic: 'Классы веществ', subtopic: 'Оксиды', difficulty: 2,
    station: 'substance-storage', interactionType: 'classification',
    prompt: 'К какому классу относится CO?', correctAnswer: 'несолеобразующий оксид', options: oxideOptions,
    explanation: 'CO при обычной классификации относят к несолеобразующим оксидам.',
    rule: 'Несолеобразующие оксиды не образуют солей в типичных кислотно-основных реакциях.',
    example: 'NO также несолеобразующий оксид.', hint: 'CO не соответствует кислотному ангидриду.',
    tags: ['classification', 'oxide', 'carbon'], parameters: { compound: 'CO' },
  }),
  makeTask(22, {
    topic: 'Ионы', subtopic: 'Кислотные остатки', difficulty: 1,
    station: 'formula-board', interactionType: 'ion-builder',
    prompt: 'Выбери сульфат-ион.', correctAnswer: 'SO4^2-', options: ['SO₄²⁻', 'SO₃²⁻', 'S²⁻', 'HSO₄⁻'],
    explanation: 'Сульфат-ион имеет формулу SO₄²⁻.', rule: 'Сульфат содержит четыре атома кислорода.',
    example: 'Ba²⁺ + SO₄²⁻ → BaSO₄.', hint: 'Ищи четыре атома кислорода и заряд −2.', tags: ['ion', 'sulfate'],
  }),
  makeTask(23, {
    topic: 'Ионы', subtopic: 'Кислотные остатки', difficulty: 1,
    station: 'formula-board', interactionType: 'ion-builder',
    prompt: 'Выбери сульфит-ион.', correctAnswer: 'SO3^2-', options: ['SO₃²⁻', 'SO₄²⁻', 'S²⁻', 'HSO₃⁻'],
    explanation: 'Сульфит-ион имеет формулу SO₃²⁻.', rule: 'Сульфит содержит на один атом кислорода меньше, чем сульфат.',
    example: 'Na₂SO₃ — сульфит натрия.', hint: 'Ищи три атома кислорода и заряд −2.', tags: ['ion', 'sulfite'],
  }),
  makeTask(24, {
    topic: 'Ионы', subtopic: 'Кислотные остатки', difficulty: 1,
    station: 'formula-board', interactionType: 'ion-builder',
    prompt: 'Выбери нитрат-ион.', correctAnswer: 'NO3^-', options: ['NO₃⁻', 'NO₂⁻', 'NH₄⁺', 'N³⁻'],
    explanation: 'Нитрат-ион имеет формулу NO₃⁻.', rule: 'Нитрат является однозарядным анионом.',
    example: 'NaNO₃ — нитрат натрия.', hint: 'Ищи три атома кислорода и заряд −1.', tags: ['ion', 'nitrate'],
  }),
  makeTask(25, {
    topic: 'Ионы', subtopic: 'Кислотные остатки', difficulty: 1,
    station: 'formula-board', interactionType: 'ion-builder',
    prompt: 'Выбери фосфат-ион.', correctAnswer: 'PO4^3-', options: ['PO₄³⁻', 'SO₄²⁻', 'CO₃²⁻', 'HPO₄²⁻'],
    explanation: 'Фосфат-ион имеет формулу PO₄³⁻.', rule: 'Фосфат несёт заряд −3.',
    example: 'Ca₃(PO₄)₂ — фосфат кальция.', hint: 'Ищи фосфор, четыре атома кислорода и заряд −3.', tags: ['ion', 'phosphate'],
  }),
  makeTask(26, {
    topic: 'Ионы', subtopic: 'Кислые остатки', difficulty: 1,
    station: 'formula-board', interactionType: 'ion-builder',
    prompt: 'Выбери гидрокарбонат-ион.', correctAnswer: 'HCO3^-', options: ['HCO₃⁻', 'CO₃²⁻', 'OH⁻', 'HSO₄⁻'],
    explanation: 'Гидрокарбонат-ион имеет формулу HCO₃⁻.', rule: 'При присоединении H⁺ к CO₃²⁻ заряд уменьшается по модулю до −1.',
    example: 'NaHCO₃ — гидрокарбонат натрия.', hint: 'В составе есть H, C и три O.', tags: ['ion', 'hydrogen-carbonate'],
  }),
  makeTask(27, {
    topic: 'Степени окисления', subtopic: 'Кислоты', difficulty: 2,
    station: 'formula-board', interactionType: 'oxidation-state',
    prompt: 'Определи степень окисления серы в H₂SO₄.', correctAnswer: '+6', acceptedAnswers: ['6+', 'VI'],
    explanation: '2·(+1) + x + 4·(−2) = 0, поэтому x = +6.',
    rule: 'Сумма степеней окисления атомов в нейтральной молекуле равна нулю.', example: 'В SO₃ сера также имеет +6.',
    hint: 'Используй H = +1 и O = −2.', tags: ['oxidation-state', 'sulfur'], parameters: { compound: 'H2SO4' },
  }),
  makeTask(28, {
    topic: 'Степени окисления', subtopic: 'Сложные соли', difficulty: 3,
    station: 'formula-board', interactionType: 'oxidation-state',
    prompt: 'Определи степень окисления хрома в K₂Cr₂O₇.', correctAnswer: '+6', acceptedAnswers: ['6+', 'VI'],
    explanation: '2·(+1) + 2x + 7·(−2) = 0, поэтому x = +6.', rule: 'Сумма степеней окисления в нейтральном соединении равна нулю.',
    example: 'В CrO₃ хром имеет +6.', hint: 'K = +1, O = −2; учти два атома Cr.',
    tags: ['oxidation-state', 'chromium'], parameters: { compound: 'K2Cr2O7' },
  }),
  makeTask(29, {
    topic: 'Степени окисления', subtopic: 'Гидриды неметаллов', difficulty: 2,
    station: 'formula-board', interactionType: 'oxidation-state',
    prompt: 'Определи степень окисления азота в NH₃.', correctAnswer: '-3', acceptedAnswers: ['3-', '-III'],
    explanation: 'x + 3·(+1) = 0, поэтому азот имеет −3.', rule: 'В соединениях с неметаллами водород обычно имеет +1.',
    example: 'В NH₄⁺ азот также имеет −3.', hint: 'Три H дают суммарно +3.', tags: ['oxidation-state', 'nitrogen'],
    parameters: { compound: 'NH3' },
  }),
  makeTask(30, {
    topic: 'Степени окисления', subtopic: 'Сложные соли', difficulty: 3,
    station: 'formula-board', interactionType: 'oxidation-state',
    prompt: 'Определи степень окисления марганца в KMnO₄.', correctAnswer: '+7', acceptedAnswers: ['7+', 'VII'],
    explanation: '(+1) + x + 4·(−2) = 0, поэтому x = +7.', rule: 'Калий имеет +1, кислород обычно −2.',
    example: 'В MnO₂ марганец имеет +4.', hint: 'Суммарный вклад четырёх O равен −8.',
    tags: ['oxidation-state', 'manganese'], parameters: { compound: 'KMnO4' },
  }),
  makeTask(31, {
    topic: 'Степени окисления', subtopic: 'Оксиды', difficulty: 2,
    station: 'formula-board', interactionType: 'oxidation-state',
    prompt: 'Определи степень окисления железа в Fe₂O₃.', correctAnswer: '+3', acceptedAnswers: ['3+', 'III'],
    explanation: '2x + 3·(−2) = 0, поэтому x = +3.', rule: 'Кислород в обычных оксидах имеет −2.',
    example: 'В FeO железо имеет +2.', hint: 'Три O дают суммарно −6; раздели +6 между двумя Fe.',
    tags: ['oxidation-state', 'iron', 'oxide'], parameters: { compound: 'Fe2O3' },
  }),
  makeTask(32, {
    topic: 'Периодическая система', subtopic: 'Валентные электроны', difficulty: 1,
    station: 'periodic-table-terminal', interactionType: 'periodic-table',
    prompt: 'Сколько валентных электронов у атома кислорода?', correctAnswer: '6', options: ['2', '4', '6', '8'],
    explanation: 'Кислород находится в 16-й группе и имеет 6 валентных электронов.', rule: 'Для элементов главных подгрупп номер группы связан с числом валентных электронов.',
    example: 'Сера также имеет 6 валентных электронов.', hint: 'Кислород находится в 16-й группе.', tags: ['periodic-table', 'oxygen', 'valence-electrons'],
  }),
  makeTask(33, {
    topic: 'Периодическая система', subtopic: 'Валентные электроны', difficulty: 1,
    station: 'periodic-table-terminal', interactionType: 'periodic-table',
    prompt: 'Сколько валентных электронов у атома натрия?', correctAnswer: '1', options: ['1', '2', '7', '8'],
    explanation: 'Натрий находится в 1-й группе и имеет один электрон на внешнем уровне.', rule: 'Щелочные металлы имеют один валентный электрон.',
    example: 'Калий также имеет один валентный электрон.', hint: 'Натрий — элемент 1-й группы.', tags: ['periodic-table', 'sodium', 'valence-electrons'],
  }),
  makeTask(34, {
    topic: 'Строение атома', subtopic: 'Электронная конфигурация', difficulty: 2,
    station: 'periodic-table-terminal', interactionType: 'periodic-table',
    prompt: 'Какому элементу соответствует конфигурация 1s² 2s² 2p⁶ 3s¹?', correctAnswer: 'натрий',
    acceptedAnswers: ['Na'], options: ['натрий', 'магний', 'неон', 'алюминий'],
    explanation: 'В конфигурации 11 электронов, значит порядковый номер элемента равен 11 — это натрий.',
    rule: 'В нейтральном атоме число электронов равно порядковому номеру.', example: '1s² 2s² 2p⁶ — неон.',
    hint: 'Сложи показатели степеней во всех орбиталях.', tags: ['atomic-structure', 'electron-configuration', 'sodium'],
  }),
  makeTask(35, {
    topic: 'Строение атома', subtopic: 'Электронная конфигурация', difficulty: 2,
    station: 'periodic-table-terminal', interactionType: 'periodic-table',
    prompt: 'Какому элементу соответствует внешний уровень 3s² 3p⁵?', correctAnswer: 'хлор',
    acceptedAnswers: ['Cl'], options: ['хлор', 'сера', 'аргон', 'фосфор'],
    explanation: 'На третьем внешнем уровне 7 электронов; элемент 3-го периода и 17-й группы — хлор.',
    rule: 'Конфигурация ns²np⁵ характерна для галогенов.', example: '2s²2p⁵ соответствует фтору.',
    hint: 'Семь валентных электронов указывает на галоген.', tags: ['atomic-structure', 'electron-configuration', 'chlorine'],
  }),
  makeTask(36, {
    topic: 'Строение атома', subtopic: 'Квантовые числа', difficulty: 2,
    station: 'periodic-table-terminal', interactionType: 'multiple-choice',
    prompt: 'Что характеризует главное квантовое число n?',
    correctAnswer: 'главный энергетический уровень электронной оболочки',
    options: ['главный энергетический уровень электронной оболочки', 'ориентацию орбитали', 'направление спина', 'только заряд ядра'],
    explanation: 'Главное квантовое число n определяет энергетический уровень и связано с размером электронной оболочки.',
    rule: 'n принимает положительные целые значения: 1, 2, 3 и далее.', example: 'Для орбиталей 3s и 3p главное квантовое число равно 3.',
    hint: 'Число n стоит перед буквенным обозначением орбитали.', tags: ['atomic-structure', 'quantum-number'],
  }),
  makeTask(37, {
    topic: 'Химическая связь', subtopic: 'Ионная связь', difficulty: 1,
    station: 'periodic-table-terminal', interactionType: 'multiple-choice',
    prompt: 'Какой тип химической связи преобладает в NaCl?', correctAnswer: 'ионная',
    options: ['ионная', 'ковалентная неполярная', 'металлическая', 'водородная'],
    explanation: 'Na передаёт электрон Cl, образуя притягивающиеся ионы Na⁺ и Cl⁻.',
    rule: 'Ионная связь возникает благодаря электростатическому притяжению противоположно заряженных ионов.',
    example: 'CaO — ионное соединение.', hint: 'Это соединение активного металла с неметаллом.',
    tags: ['bonding', 'ionic', 'sodium-chloride'], parameters: { compound: 'NaCl' },
  }),
  makeTask(38, {
    topic: 'Химическая связь', subtopic: 'Ковалентная связь', difficulty: 1,
    station: 'periodic-table-terminal', interactionType: 'multiple-choice',
    prompt: 'Какая связь существует между атомами в молекуле H₂?', correctAnswer: 'ковалентная неполярная',
    options: ['ковалентная неполярная', 'ковалентная полярная', 'ионная', 'металлическая'],
    explanation: 'Одинаковые атомы водорода делят электронную пару поровну.',
    rule: 'Связь между одинаковыми атомами неметалла является ковалентной неполярной.',
    example: 'Связь в O₂ также ковалентная неполярная.', hint: 'Электроотрицательности двух атомов одинаковы.',
    tags: ['bonding', 'covalent', 'hydrogen'], parameters: { compound: 'H2' },
  }),
  makeTask(39, {
    topic: 'Химическая связь', subtopic: 'Металлическая связь', difficulty: 1,
    station: 'periodic-table-terminal', interactionType: 'multiple-choice',
    prompt: 'Какой тип связи характерен для металлического железа?', correctAnswer: 'металлическая',
    options: ['металлическая', 'ионная', 'ковалентная неполярная', 'водородная'],
    explanation: 'В металлическом железе катионные остовы удерживаются общими делокализованными электронами.',
    rule: 'Металлическая связь характерна для простых веществ-металлов и сплавов.',
    example: 'В металлической меди связь также металлическая.', hint: 'Железо здесь рассматривается как простое вещество-металл.',
    tags: ['bonding', 'metallic', 'iron'], parameters: { compound: 'Fe' },
  }),
  makeTask(40, {
    topic: 'Классы веществ', subtopic: 'Сортировка', difficulty: 2,
    station: 'substance-storage', interactionType: 'sorting',
    prompt: 'Выбери полностью правильную сортировку HCl, NaOH, CO₂ и K₂SO₄.',
    correctAnswer: 'HCl — кислота; NaOH — основание; CO₂ — кислотный оксид; K₂SO₄ — соль',
    options: [
      'HCl — кислота; NaOH — основание; CO₂ — кислотный оксид; K₂SO₄ — соль',
      'HCl — соль; NaOH — кислота; CO₂ — основной оксид; K₂SO₄ — основание',
      'HCl — кислота; NaOH — соль; CO₂ — несолеобразующий оксид; K₂SO₄ — кислота',
      'HCl — основание; NaOH — кислота; CO₂ — амфотерный оксид; K₂SO₄ — соль',
    ],
    explanation: 'HCl — кислота, NaOH — основание, CO₂ — кислотный оксид, K₂SO₄ — соль.',
    rule: 'Класс вещества определяют по составу и характерным химическим свойствам.',
    example: 'H₂SO₄ — кислота, CaO — основный оксид.', hint: 'Начни с легко узнаваемых HCl и NaOH.',
    tags: ['classification', 'sorting', 'acid', 'base', 'oxide', 'salt'],
  }),
] as const
