import type { StationDefinition } from '../types'

export const STATIONS: readonly StationDefinition[] = [
  {
    id: 'periodic-terminal',
    name: 'Периодическая система',
    shortName: 'Таблица',
    description: 'Атомы, электронные конфигурации и периодические свойства.',
    stationType: 'periodic-table-terminal',
    position: [-7.5, 0, -4.8],
    accent: '#33c8ff',
    icon: 'e⁻',
    interactionRadius: 2.25,
  },
  {
    id: 'substance-storage',
    name: 'Склад веществ',
    shortName: 'Склад',
    description: 'Определи вещество, его класс и строительное применение.',
    stationType: 'substance-storage',
    position: [-2.6, 0, -6.2],
    accent: '#ffc83d',
    icon: '▤',
    interactionRadius: 2.35,
  },
  {
    id: 'formula-board',
    name: 'Формульная доска',
    shortName: 'Формулы',
    description: 'Собирай формулы из ионов и проверяй заряды.',
    stationType: 'formula-board',
    position: [3.1, 0, -4.4],
    accent: '#a87cff',
    icon: 'ƒx',
    interactionRadius: 2.25,
  },
  {
    id: 'reaction-bench',
    name: 'Реакционный стенд',
    shortName: 'Реакции',
    description: 'Завершай и балансируй химические уравнения.',
    stationType: 'reaction-bench',
    position: [8.1, 0, -2.4],
    accent: '#ff7a59',
    icon: '⇌',
    interactionRadius: 2.35,
  },
  {
    id: 'mixing-station',
    name: 'Станция смешивания',
    shortName: 'Смешивание',
    description: 'Проводи безопасные виртуальные реакции растворов.',
    stationType: 'mixing-station',
    position: [8.0, 0, 3.4],
    accent: '#4de2a8',
    icon: '⚗',
    interactionRadius: 2.4,
  },
  {
    id: 'solution-lab',
    name: 'Лаборатория растворов',
    shortName: 'Растворы',
    description: 'Готовь растворы и работай с концентрациями.',
    stationType: 'solution-laboratory',
    position: [3.3, 0, 6.25],
    accent: '#54d6ef',
    icon: 'mL',
    interactionRadius: 2.3,
  },
  {
    id: 'ionic-reaction',
    name: 'Ионный реактор',
    shortName: 'Ионы',
    description: 'Собирай полные и сокращённые ионные уравнения.',
    stationType: 'ionic-reaction-station',
    position: [-8.1, 0, 0.25],
    accent: '#478dff',
    icon: '±',
    interactionRadius: 2.3,
  },
  {
    id: 'inspection',
    name: 'Пункт инспекции',
    shortName: 'Инспекция',
    description: 'Сдавай этапы и диагностируй строительные материалы.',
    stationType: 'inspection-station',
    position: [-4.2, 0, 6.2],
    accent: '#f2a93b',
    icon: '✓',
    interactionRadius: 2.45,
  },
  {
    id: 'electrochemistry',
    name: 'Электрохимический пост',
    shortName: 'Электрохимия',
    description: 'Исследуй электроды, гальванические процессы и перенос электронов.',
    stationType: 'electrochemistry-station',
    position: [0.2, 0, -7.0],
    accent: '#3bd4c5',
    icon: 'e−',
    interactionRadius: 2.3,
  },
  {
    id: 'corrosion-rig',
    name: 'Стенд коррозии',
    shortName: 'Коррозия',
    description: 'Диагностируй состояние стали и выбирай принцип защиты.',
    stationType: 'corrosion-test-rig',
    position: [-8.8, 0, 4.0],
    accent: '#e16f46',
    icon: 'Fe',
    interactionRadius: 2.35,
  },
  {
    id: 'materials-lab',
    name: 'Лаборатория материалов',
    shortName: 'Материалы',
    description: 'Испытывай цемент, бетон, известь, гипс и строительную воду.',
    stationType: 'construction-materials-station',
    position: [8.7, 0, 6.35],
    accent: '#e7b84d',
    icon: 'MPa',
    interactionRadius: 2.4,
  },
] as const

export const getStation = (stationId: string | null) =>
  STATIONS.find((station) => station.id === stationId) ?? null
