import type { TaskDefinition } from '../types'

type LevelTwoInput = Omit<TaskDefinition, 'id' | 'level' | 'points' | 'procedural' | 'reviewStatus'>

const makeTask = (number: number, definition: LevelTwoInput): TaskDefinition => ({
  ...definition,
  id: `L2-${String(number).padStart(3, '0')}`,
  level: 2,
  points: 120,
  procedural: false,
  reviewStatus: 'verified',
})

const reactionRule = 'Число атомов каждого элемента сохраняется в химической реакции.'
const balanceHint = 'Подбери наименьшие целые коэффициенты и пересчитай атомы с обеих сторон.'

export const level2Tasks: readonly TaskDefinition[] = [
  makeTask(41, { topic: 'Химические реакции', subtopic: 'Соединение', difficulty: 1, station: 'reaction-bench', interactionType: 'equation-completion', prompt: 'Закончи реакцию: CaO + H₂O → ?', correctAnswer: 'CaO + H2O -> Ca(OH)2', explanation: 'Оксид кальция соединяется с водой с образованием гидроксида кальция.', rule: reactionRule, example: 'CaO + H₂O → Ca(OH)₂.', hint: 'Продукт — гашёная известь.', tags: ['reaction', 'lime', 'construction'], parameters: { compound: 'CaO' }, constructionContext: 'Реакция лежит в основе гашения извести.' }),
  makeTask(42, { topic: 'Химические реакции', subtopic: 'Соединение', difficulty: 1, station: 'reaction-bench', interactionType: 'equation-completion', prompt: 'Закончи реакцию: SO₃ + H₂O → ?', correctAnswer: 'SO3 + H2O -> H2SO4', explanation: 'Кислотный оксид SO₃ с водой образует серную кислоту.', rule: 'Кислотный оксид с водой может образовывать соответствующую кислоту.', example: 'SO₃ + H₂O → H₂SO₄.', hint: 'Продукт содержит два H, одну S и четыре O.', tags: ['reaction', 'acidic-oxide'], parameters: { compound: 'SO3' } }),
  makeTask(43, { topic: 'Химические реакции', subtopic: 'Нейтрализация', difficulty: 1, station: 'reaction-bench', interactionType: 'equation-completion', prompt: 'Закончи реакцию: NaOH + HCl → ?', correctAnswer: 'NaOH + HCl -> NaCl + H2O', explanation: 'Сильная кислота и щёлочь образуют соль и воду.', rule: 'Нейтрализация: кислота + основание → соль + вода.', example: 'KOH + HNO₃ → KNO₃ + H₂O.', hint: 'Собери соль из Na⁺ и Cl⁻.', tags: ['reaction', 'neutralization'], parameters: { compound: 'NaOH' } }),
  makeTask(44, { topic: 'Химические реакции', subtopic: 'Разложение', difficulty: 1, station: 'reaction-bench', interactionType: 'equation-completion', prompt: 'Закончи разложение: CaCO₃ → ?', correctAnswer: 'CaCO3 -> CaO + CO2', explanation: 'При нагревании карбонат кальция разлагается на оксид кальция и углекислый газ.', rule: reactionRule, example: 'CaCO₃ → CaO + CO₂.', hint: 'Это реакция обжига известняка.', tags: ['reaction', 'decomposition', 'construction'], parameters: { compound: 'CaCO3' }, constructionContext: 'Обжиг известняка даёт негашёную известь.' }),
  makeTask(45, { topic: 'Химические реакции', subtopic: 'Металл и кислота', difficulty: 1, station: 'reaction-bench', interactionType: 'equation-completion', prompt: 'Закончи реакцию: Zn + 2HCl → ?', correctAnswer: 'Zn + 2HCl -> ZnCl2 + H2', explanation: 'Цинк вытесняет водород из соляной кислоты, образуя ZnCl₂ и H₂.', rule: 'Металл выше водорода в ряду активности реагирует с разбавленной неокисляющей кислотой.', example: 'Mg + 2HCl → MgCl₂ + H₂.', hint: 'Продукты — хлорид цинка и водород.', tags: ['reaction', 'activity-series', 'gas'], parameters: { compound: 'Zn' } }),
  makeTask(46, { topic: 'Уравнивание реакций', subtopic: 'Окисление металлов', difficulty: 2, station: 'reaction-bench', interactionType: 'equation-balancing', prompt: 'Расставь коэффициенты: Al + O₂ → Al₂O₃.', correctAnswer: '4Al + 3O2 -> 2Al2O3', explanation: 'Коэффициенты 4:3:2 дают по 4 Al и 6 O с каждой стороны.', rule: reactionRule, example: '4Al + 3O₂ → 2Al₂O₃.', hint: balanceHint, tags: ['balancing', 'aluminium', 'oxygen'], parameters: { compound: 'Al2O3' } }),
  makeTask(47, { topic: 'Уравнивание реакций', subtopic: 'Окисление металлов', difficulty: 2, station: 'reaction-bench', interactionType: 'equation-balancing', prompt: 'Расставь коэффициенты: Fe + O₂ → Fe₂O₃.', correctAnswer: '4Fe + 3O2 -> 2Fe2O3', explanation: 'Коэффициенты 4:3:2 сохраняют четыре атома Fe и шесть атомов O.', rule: reactionRule, example: '4Fe + 3O₂ → 2Fe₂O₃.', hint: balanceHint, tags: ['balancing', 'iron', 'oxygen'], parameters: { compound: 'Fe2O3' } }),
  makeTask(48, { topic: 'Уравнивание реакций', subtopic: 'Реакции соединения', difficulty: 1, station: 'reaction-bench', interactionType: 'equation-balancing', prompt: 'Расставь коэффициенты: H₂ + O₂ → H₂O.', correctAnswer: '2H2 + O2 -> 2H2O', explanation: 'Две молекулы H₂ и одна O₂ образуют две молекулы H₂O.', rule: reactionRule, example: '2H₂ + O₂ → 2H₂O.', hint: 'Сначала уравняй кислород коэффициентом 2 перед водой.', tags: ['balancing', 'hydrogen', 'water'], parameters: { compound: 'H2O' } }),
  makeTask(49, { topic: 'Уравнивание реакций', subtopic: 'Металл и вода', difficulty: 2, station: 'reaction-bench', interactionType: 'equation-balancing', prompt: 'Расставь коэффициенты: Na + H₂O → NaOH + H₂.', correctAnswer: '2Na + 2H2O -> 2NaOH + H2', explanation: 'Коэффициенты 2:2:2:1 сохраняют Na, H и O.', rule: reactionRule, example: '2Na + 2H₂O → 2NaOH + H₂.', hint: 'Водород выделяется двухатомными молекулами.', tags: ['balancing', 'sodium', 'water'], parameters: { compound: 'Na' } }),
  makeTask(50, { topic: 'Уравнивание реакций', subtopic: 'Окисление неметаллов', difficulty: 2, station: 'reaction-bench', interactionType: 'equation-balancing', prompt: 'Расставь коэффициенты: P + O₂ → P₂O₅.', correctAnswer: '4P + 5O2 -> 2P2O5', explanation: 'Коэффициенты 4:5:2 дают четыре P и десять O с каждой стороны.', rule: reactionRule, example: '4P + 5O₂ → 2P₂O₅.', hint: 'Сделай число атомов кислорода равным 10.', tags: ['balancing', 'phosphorus', 'oxygen'], parameters: { compound: 'P2O5' } }),
  makeTask(51, { topic: 'Реакции обмена', subtopic: 'Осаждение', difficulty: 2, station: 'mixing-station', interactionType: 'virtual-mixing', prompt: 'Запиши реакцию смешивания BaCl₂ и Na₂SO₄.', correctAnswer: 'BaCl2 + Na2SO4 -> BaSO4 + 2NaCl', explanation: 'Ba²⁺ и SO₄²⁻ образуют малорастворимый белый BaSO₄.', rule: 'Реакция обмена идёт до конца при образовании осадка.', example: 'Ba²⁺ + SO₄²⁻ → BaSO₄↓.', hint: 'Нерастворимый продукт содержит Ba²⁺ и SO₄²⁻.', tags: ['mixing', 'precipitate', 'sulfate'], parameters: { compound: 'BaSO4', mixingReagents: ['BaCl₂', 'Na₂SO₄'], mixingOptions: ['BaCl₂', 'Na₂SO₄', 'NaCl', 'H₂O'], mixingObservation: 'Белый осадок BaSO₄' } }),
  makeTask(52, { topic: 'Реакции обмена', subtopic: 'Осаждение', difficulty: 2, station: 'mixing-station', interactionType: 'virtual-mixing', prompt: 'Запиши реакцию смешивания AgNO₃ и NaCl.', correctAnswer: 'AgNO3 + NaCl -> AgCl + NaNO3', explanation: 'Ag⁺ и Cl⁻ образуют малорастворимый белый AgCl.', rule: 'Нитраты растворимы, а AgCl выпадает в осадок.', example: 'Ag⁺ + Cl⁻ → AgCl↓.', hint: 'Осадок образуют ионы Ag⁺ и Cl⁻.', tags: ['mixing', 'precipitate', 'chloride'], parameters: { compound: 'AgCl', mixingReagents: ['AgNO₃', 'NaCl'], mixingOptions: ['AgNO₃', 'NaCl', 'NaNO₃', 'H₂O'], mixingObservation: 'Белый осадок AgCl' } }),
  makeTask(53, { topic: 'Реакции обмена', subtopic: 'Осаждение гидроксидов', difficulty: 2, station: 'mixing-station', interactionType: 'virtual-mixing', prompt: 'Закончи реакцию: CuSO₄ + 2NaOH → ?', correctAnswer: 'CuSO4 + 2NaOH -> Cu(OH)2 + Na2SO4', explanation: 'Cu²⁺ с OH⁻ образует малорастворимый Cu(OH)₂.', rule: 'Большинство гидроксидов переходных металлов малорастворимы.', example: 'Cu²⁺ + 2OH⁻ → Cu(OH)₂↓.', hint: 'Осадок — гидроксид меди(II).', tags: ['mixing', 'precipitate', 'hydroxide'], parameters: { compound: 'Cu(OH)2', mixingReagents: ['CuSO₄', 'NaOH'], mixingOptions: ['CuSO₄', 'NaOH', 'Na₂SO₄', 'H₂O'], mixingObservation: 'Голубой осадок Cu(OH)₂' } }),
  makeTask(54, { topic: 'Реакции обмена', subtopic: 'Осаждение гидроксидов', difficulty: 2, station: 'mixing-station', interactionType: 'virtual-mixing', prompt: 'Закончи реакцию: FeCl₃ + 3NaOH → ?', correctAnswer: 'FeCl3 + 3NaOH -> Fe(OH)3 + 3NaCl', explanation: 'Fe³⁺ с тремя OH⁻ образует малорастворимый Fe(OH)₃.', rule: 'Заряд Fe³⁺ требует три гидроксид-иона.', example: 'Fe³⁺ + 3OH⁻ → Fe(OH)₃↓.', hint: 'Осадок содержит Fe³⁺ и три OH⁻.', tags: ['mixing', 'precipitate', 'iron'], parameters: { compound: 'Fe(OH)3', mixingReagents: ['FeCl₃', 'NaOH'], mixingOptions: ['FeCl₃', 'NaOH', 'NaCl', 'H₂O'], mixingObservation: 'Бурый осадок Fe(OH)₃' } }),
  makeTask(55, { topic: 'Реакции обмена', subtopic: 'Выделение газа', difficulty: 2, station: 'mixing-station', interactionType: 'virtual-mixing', prompt: 'Закончи реакцию: Na₂CO₃ + 2HCl → ?', correctAnswer: 'Na2CO3 + 2HCl -> 2NaCl + H2O + CO2', explanation: 'Карбонат с сильной кислотой даёт соль, воду и CO₂.', rule: 'Угольная кислота неустойчива и распадается на H₂O и CO₂.', example: 'CO₃²⁻ + 2H⁺ → H₂O + CO₂↑.', hint: 'Газообразный продукт — углекислый газ.', tags: ['mixing', 'gas', 'carbonate'], parameters: { compound: 'CO2', mixingReagents: ['Na₂CO₃', 'HCl'], mixingOptions: ['Na₂CO₃', 'HCl', 'NaCl', 'H₂O'], mixingObservation: 'Выделяется CO₂' } }),
  makeTask(56, { topic: 'Признаки реакций', subtopic: 'Выделение газа', difficulty: 1, station: 'mixing-station', interactionType: 'gas-identification', prompt: 'Какой газ выделяется при взаимодействии карбонатов с сильной кислотой?', correctAnswer: 'CO2', acceptedAnswers: ['углекислый газ', 'диоксид углерода'], options: ['CO₂', 'H₂', 'O₂', 'NH₃'], explanation: 'Ионы CO₃²⁻ с H⁺ образуют H₂CO₃, которая распадается на H₂O и CO₂.', rule: 'Карбонат + кислота сопровождается выделением CO₂.', example: 'CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂.', hint: 'Этот газ образуется при распаде угольной кислоты.', tags: ['gas', 'carbonate'], parameters: { compound: 'CO2' } }),
  makeTask(57, { topic: 'Растворимость', subtopic: 'Получение осадка', difficulty: 2, station: 'mixing-station', interactionType: 'precipitate-prediction', prompt: 'Какая пара растворов образует осадок BaSO₄?', correctAnswer: 'BaCl2 + Na2SO4', options: ['BaCl₂ + Na₂SO₄', 'NaCl + KNO₃', 'HCl + NaOH', 'K₂SO₄ + NaNO₃'], explanation: 'BaCl₂ даёт Ba²⁺, а Na₂SO₄ — SO₄²⁻; их сочетание образует BaSO₄.', rule: 'Оба реагента должны быть растворимыми источниками нужных ионов.', example: 'BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl.', hint: 'Найди растворимые источники Ba²⁺ и SO₄²⁻.', tags: ['solubility', 'precipitate', 'sulfate'], parameters: { compound: 'BaSO4' } }),
  makeTask(58, { topic: 'Растворимость', subtopic: 'Получение осадка', difficulty: 2, station: 'mixing-station', interactionType: 'precipitate-prediction', prompt: 'Какая пара растворов образует осадок AgCl?', correctAnswer: 'AgNO3 + NaCl', options: ['AgNO₃ + NaCl', 'NaNO₃ + KCl', 'Ag + HCl', 'NaCl + KOH'], explanation: 'AgNO₃ даёт Ag⁺, а NaCl — Cl⁻; образуется AgCl.', rule: 'AgCl малорастворим в воде.', example: 'Ag⁺ + Cl⁻ → AgCl↓.', hint: 'Найди растворимые источники Ag⁺ и Cl⁻.', tags: ['solubility', 'precipitate', 'chloride'], parameters: { compound: 'AgCl' } }),
  makeTask(59, { topic: 'Растворимость', subtopic: 'Растворимые соли', difficulty: 1, station: 'mixing-station', interactionType: 'precipitate-prediction', prompt: 'Выпадает ли NaCl в осадок в обычной реакции обмена разбавленных растворов?', correctAnswer: 'нет', options: ['нет', 'да, всегда', 'только при нейтрализации', 'только с нитратами'], explanation: 'NaCl хорошо растворим в воде и обычно остаётся в растворе.', rule: 'Большинство солей натрия растворимы.', example: 'NaNO₃ также хорошо растворим.', hint: 'Вспомни правило растворимости солей натрия.', tags: ['solubility', 'sodium-chloride'], parameters: { compound: 'NaCl' } }),
  makeTask(60, { topic: 'Растворимость', subtopic: 'Малорастворимые соли', difficulty: 1, station: 'mixing-station', interactionType: 'precipitate-prediction', prompt: 'Как характеризуется растворимость CaCO₃ в воде?', correctAnswer: 'практически нерастворим', acceptedAnswers: ['малорастворим', 'малорастворимое вещество'], options: ['практически нерастворим', 'хорошо растворим', 'полностью смешивается', 'является газом'], explanation: 'CaCO₃ имеет очень низкую растворимость в воде.', rule: 'Большинство карбонатов, кроме солей щелочных металлов и аммония, малорастворимы.', example: 'MgCO₃ также малорастворим.', hint: 'Известняк сохраняется в воде как твёрдая фаза.', tags: ['solubility', 'carbonate', 'construction'], parameters: { compound: 'CaCO3' } }),
  makeTask(61, { topic: 'Ионные уравнения', subtopic: 'Нейтрализация', difficulty: 2, station: 'ionic-reaction-station', interactionType: 'ionic-equation', prompt: 'Напиши сокращённое ионное уравнение нейтрализации сильной кислоты сильной щёлочью.', correctAnswer: 'H+ + OH- -> H2O', explanation: 'Ионы H⁺ и OH⁻ соединяются в слабодиссоциирующую воду.', rule: 'Ионы-наблюдатели исключают из сокращённого ионного уравнения.', example: 'H⁺ + OH⁻ → H₂O.', hint: 'Оставь только ионы, которые образуют воду.', tags: ['ionic-equation', 'neutralization'], parameters: { compound: 'H2O' } }),
  makeTask(62, { topic: 'Ионные уравнения', subtopic: 'Осаждение', difficulty: 2, station: 'ionic-reaction-station', interactionType: 'ionic-equation', prompt: 'Напиши сокращённое ионное уравнение образования BaSO₄.', correctAnswer: 'Ba^2+ + SO4^2- -> BaSO4', explanation: 'Ba²⁺ и SO₄²⁻ непосредственно образуют осадок BaSO₄.', rule: 'В сокращённом уравнении сохраняют частицы, участвующие в превращении.', example: 'Ba²⁺ + SO₄²⁻ → BaSO₄↓.', hint: 'Соедини катион бария и сульфат-ион.', tags: ['ionic-equation', 'precipitate', 'sulfate'], parameters: { compound: 'BaSO4' } }),
  makeTask(63, { topic: 'Ионные уравнения', subtopic: 'Осаждение', difficulty: 2, station: 'ionic-reaction-station', interactionType: 'ionic-equation', prompt: 'Напиши сокращённое ионное уравнение образования AgCl.', correctAnswer: 'Ag+ + Cl- -> AgCl', explanation: 'Ag⁺ и Cl⁻ образуют малорастворимый AgCl.', rule: 'Заряды и число атомов должны сохраняться.', example: 'Ag⁺ + Cl⁻ → AgCl↓.', hint: 'У каждого исходного иона заряд по модулю равен 1.', tags: ['ionic-equation', 'precipitate', 'chloride'], parameters: { compound: 'AgCl' } }),
  makeTask(64, { topic: 'Ионные уравнения', subtopic: 'Осаждение гидроксидов', difficulty: 2, station: 'ionic-reaction-station', interactionType: 'ionic-equation', prompt: 'Напиши сокращённое ионное уравнение образования Cu(OH)₂.', correctAnswer: 'Cu^2+ + 2OH- -> Cu(OH)2', explanation: 'Одному Cu²⁺ нужны два OH⁻ для образования нейтрального осадка.', rule: 'Суммарный заряд левой части должен совпадать с правой.', example: 'Cu²⁺ + 2OH⁻ → Cu(OH)₂↓.', hint: 'Уравняй заряд Cu²⁺ двумя гидроксид-ионами.', tags: ['ionic-equation', 'hydroxide', 'copper'], parameters: { compound: 'Cu(OH)2' } }),
  makeTask(65, { topic: 'Ионные уравнения', subtopic: 'Ионы-наблюдатели', difficulty: 2, station: 'ionic-reaction-station', interactionType: 'multiple-choice', prompt: 'Какие ионы являются наблюдателями в реакции HCl + NaOH → NaCl + H₂O?', correctAnswer: 'Na+ и Cl-', acceptedAnswers: ['Na+, Cl-'], options: ['Na⁺ и Cl⁻', 'H⁺ и OH⁻', 'Na⁺ и OH⁻', 'H⁺ и Cl⁻'], explanation: 'Na⁺ и Cl⁻ присутствуют в растворе до и после реакции без изменения.', rule: 'Ионы-наблюдатели сокращаются при переходе к сокращённому ионному уравнению.', example: 'Остаётся H⁺ + OH⁻ → H₂O.', hint: 'Найди ионы, не вошедшие в состав воды.', tags: ['ionic-equation', 'spectator-ions'], parameters: { compound: 'NaCl' } }),
  makeTask(66, { topic: 'Ряд активности', subtopic: 'Вытеснение металлов', difficulty: 1, station: 'reaction-bench', interactionType: 'activity-series', prompt: 'Будет ли Zn реагировать с раствором CuSO₄?', correctAnswer: 'да', options: ['да', 'нет'], explanation: 'Цинк активнее меди и вытесняет её из раствора соли.', rule: 'Более активный металл вытесняет менее активный из раствора его соли.', example: 'Zn + CuSO₄ → ZnSO₄ + Cu.', hint: 'Сравни положение Zn и Cu в ряду активности.', tags: ['activity-series', 'zinc', 'copper'] }),
  makeTask(67, { topic: 'Ряд активности', subtopic: 'Вытеснение металлов', difficulty: 1, station: 'reaction-bench', interactionType: 'activity-series', prompt: 'Будет ли Cu вытеснять Zn из раствора ZnSO₄?', correctAnswer: 'нет', options: ['нет', 'да'], explanation: 'Медь менее активна, чем цинк, и не вытесняет его из соли.', rule: 'Вытеснение возможно только более активным металлом.', example: 'Cu + ZnSO₄ — реакции нет.', hint: 'Медь расположена ниже цинка в ряду активности.', tags: ['activity-series', 'zinc', 'copper'] }),
  makeTask(68, { topic: 'Ряд активности', subtopic: 'Вытеснение металлов', difficulty: 2, station: 'reaction-bench', interactionType: 'equation-completion', prompt: 'Закончи реакцию: Fe + CuSO₄ → ?', correctAnswer: 'Fe + CuSO4 -> FeSO4 + Cu', explanation: 'Железо активнее меди и вытесняет её из CuSO₄.', rule: 'Более активный металл занимает место менее активного в соли.', example: 'Fe + CuSO₄ → FeSO₄ + Cu.', hint: 'Железо переходит в раствор как Fe²⁺.', tags: ['activity-series', 'iron', 'copper'] }),
  makeTask(69, { topic: 'Ряд активности', subtopic: 'Металл и кислота', difficulty: 1, station: 'reaction-bench', interactionType: 'activity-series', prompt: 'Будет ли Cu выделять H₂ из разбавленной HCl?', correctAnswer: 'нет', options: ['нет', 'да'], explanation: 'Медь находится ниже водорода в ряду активности и не вытесняет его из HCl.', rule: 'Металлы ниже водорода не выделяют H₂ из разбавленных неокисляющих кислот.', example: 'Cu + HCl — реакции нет.', hint: 'Сравни положение Cu с водородом.', tags: ['activity-series', 'copper', 'acid'] }),
  makeTask(70, { topic: 'Ряд активности', subtopic: 'Металл и кислота', difficulty: 1, station: 'reaction-bench', interactionType: 'activity-series', prompt: 'Будет ли Mg реагировать с HCl?', correctAnswer: 'да, с выделением H2', acceptedAnswers: ['да', 'да, с выделением водорода'], options: ['да, с выделением H₂', 'нет', 'да, с выделением O₂', 'только с образованием осадка'], explanation: 'Магний расположен выше водорода и вытесняет его из HCl.', rule: 'Активный металл + разбавленная кислота → соль + H₂.', example: 'Mg + 2HCl → MgCl₂ + H₂.', hint: 'Магний выше водорода в ряду активности.', tags: ['activity-series', 'magnesium', 'acid'] }),
  makeTask(71, { topic: 'Окислительно-восстановительные реакции', subtopic: 'Окисление', difficulty: 1, station: 'reaction-bench', interactionType: 'redox', prompt: 'Что происходит в переходе Fe⁰ → Fe²⁺?', correctAnswer: 'окисление, отдача двух электронов', options: ['окисление, отдача двух электронов', 'восстановление, принятие двух электронов', 'нейтрализация', 'осаждение'], explanation: 'Степень окисления Fe возрастает от 0 до +2, атом отдаёт 2e⁻.', rule: 'Окисление — отдача электронов и повышение степени окисления.', example: 'Fe → Fe²⁺ + 2e⁻.', hint: 'Степень окисления увеличивается.', tags: ['redox', 'oxidation', 'iron'] }),
  makeTask(72, { topic: 'Окислительно-восстановительные реакции', subtopic: 'Восстановление', difficulty: 1, station: 'reaction-bench', interactionType: 'redox', prompt: 'Что происходит в переходе Cu²⁺ → Cu⁰?', correctAnswer: 'восстановление, принятие двух электронов', options: ['восстановление, принятие двух электронов', 'окисление, отдача двух электронов', 'диссоциация', 'нейтрализация'], explanation: 'Степень окисления Cu уменьшается от +2 до 0, ион принимает 2e⁻.', rule: 'Восстановление — принятие электронов и снижение степени окисления.', example: 'Cu²⁺ + 2e⁻ → Cu.', hint: 'Степень окисления уменьшается.', tags: ['redox', 'reduction', 'copper'] }),
  makeTask(73, { topic: 'Окислительно-восстановительные реакции', subtopic: 'Восстановитель', difficulty: 2, station: 'reaction-bench', interactionType: 'redox', prompt: 'Кто является восстановителем в Zn + Cu²⁺ → Zn²⁺ + Cu?', correctAnswer: 'Zn', acceptedAnswers: ['цинк'], options: ['Zn', 'Cu²⁺', 'Zn²⁺', 'Cu'], explanation: 'Zn отдаёт электроны и сам окисляется, поэтому он восстановитель.', rule: 'Восстановитель отдаёт электроны.', example: 'Zn → Zn²⁺ + 2e⁻.', hint: 'Найди частицу, степень окисления которой повышается.', tags: ['redox', 'reducing-agent', 'zinc'] }),
  makeTask(74, { topic: 'Окислительно-восстановительные реакции', subtopic: 'Окислитель', difficulty: 2, station: 'reaction-bench', interactionType: 'redox', prompt: 'Кто является окислителем в Zn + Cu²⁺ → Zn²⁺ + Cu?', correctAnswer: 'Cu^2+', acceptedAnswers: ['ион меди(II)', 'Cu²⁺'], options: ['Cu²⁺', 'Zn', 'Zn²⁺', 'Cu'], explanation: 'Cu²⁺ принимает электроны и восстанавливается, поэтому это окислитель.', rule: 'Окислитель принимает электроны.', example: 'Cu²⁺ + 2e⁻ → Cu.', hint: 'Найди частицу, степень окисления которой снижается.', tags: ['redox', 'oxidizing-agent', 'copper'] }),
  makeTask(75, { topic: 'Окислительно-восстановительные реакции', subtopic: 'Электронный баланс', difficulty: 1, station: 'reaction-bench', interactionType: 'redox', prompt: 'Сколько электронов отдаёт Al при переходе Al⁰ → Al³⁺?', correctAnswer: '3', acceptedAnswers: ['3 электрона', '3e-'], options: ['3', '1', '2', '6'], explanation: 'Степень окисления возрастает на три единицы, поэтому Al отдаёт 3e⁻.', rule: 'Число отданных электронов равно увеличению степени окисления.', example: 'Al → Al³⁺ + 3e⁻.', hint: 'Вычти начальную степень окисления из конечной.', tags: ['redox', 'electron-balance', 'aluminium'] }),
  makeTask(76, { topic: 'Типы реакций', subtopic: 'Разложение', difficulty: 1, station: 'reaction-bench', interactionType: 'multiple-choice', prompt: 'Определи тип реакции: CaCO₃ → CaO + CO₂.', correctAnswer: 'реакция разложения', options: ['реакция разложения', 'реакция соединения', 'реакция замещения', 'реакция обмена'], explanation: 'Из одного сложного вещества образуются два продукта.', rule: 'При разложении одно вещество даёт несколько веществ.', example: '2KClO₃ → 2KCl + 3O₂.', hint: 'Посчитай число реагентов и продуктов.', tags: ['reaction-type', 'decomposition'], parameters: { compound: 'CaCO3' } }),
  makeTask(77, { topic: 'Типы реакций', subtopic: 'Замещение', difficulty: 1, station: 'reaction-bench', interactionType: 'multiple-choice', prompt: 'Определи тип реакции: Zn + CuSO₄ → ZnSO₄ + Cu.', correctAnswer: 'реакция замещения', options: ['реакция замещения', 'реакция соединения', 'реакция разложения', 'реакция обмена'], explanation: 'Цинк замещает медь в составе соли.', rule: 'В реакции замещения простое вещество вытесняет элемент из сложного.', example: 'Fe + CuSO₄ → FeSO₄ + Cu.', hint: 'Один металл занимает место другого.', tags: ['reaction-type', 'displacement'] }),
  makeTask(78, { topic: 'Типы реакций', subtopic: 'Обмен и нейтрализация', difficulty: 1, station: 'reaction-bench', interactionType: 'multiple-choice', prompt: 'Определи тип реакции: HCl + NaOH → NaCl + H₂O.', correctAnswer: 'реакция обмена, нейтрализация', options: ['реакция обмена, нейтрализация', 'реакция замещения', 'реакция разложения', 'реакция соединения'], explanation: 'Кислота и основание обмениваются ионами с образованием соли и воды.', rule: 'Нейтрализация является реакцией обмена.', example: 'HNO₃ + KOH → KNO₃ + H₂O.', hint: 'Реагируют кислота и щёлочь.', tags: ['reaction-type', 'neutralization'] }),
  makeTask(79, { topic: 'Типы реакций', subtopic: 'Соединение', difficulty: 1, station: 'reaction-bench', interactionType: 'multiple-choice', prompt: 'Определи тип реакции: 2H₂ + O₂ → 2H₂O.', correctAnswer: 'реакция соединения', options: ['реакция соединения', 'реакция разложения', 'реакция замещения', 'реакция обмена'], explanation: 'Из двух простых веществ образуется одно сложное вещество.', rule: 'В реакции соединения несколько веществ дают один продукт.', example: 'CaO + H₂O → Ca(OH)₂.', hint: 'Сравни число реагентов и типов продуктов.', tags: ['reaction-type', 'combination'] }),
  makeTask(80, { topic: 'Химические реакции', subtopic: 'Комплексная миссия', difficulty: 3, station: 'inspection-station', interactionType: 'construction-mission', prompt: 'Выбери набор из трёх реакций, который последовательно демонстрирует осадок, газ и образование воды.', correctAnswer: 'AgNO3 + NaCl; Na2CO3 + HCl; HCl + NaOH', options: ['AgNO₃ + NaCl; Na₂CO₃ + HCl; HCl + NaOH', 'NaCl + KNO₃; HCl + NaOH; AgNO₃ + NaCl', 'HCl + NaOH; NaCl + KNO₃; CuSO₄ + NaCl', 'Zn + CuSO₄; NaOH + KCl; HCl + NaCl'], explanation: 'Первая реакция даёт AgCl↓, вторая — CO₂↑, третья — H₂O.', rule: 'Признаки реакции включают образование осадка, газа или слабого электролита.', example: 'Ag⁺ + Cl⁻ → AgCl↓.', hint: 'Проверь по одному требуемому признаку в каждой позиции.', tags: ['mission', 'precipitate', 'gas', 'neutralization'] }),
] as const
