import type { TaskDefinition } from '../types'

type LevelFiveInput = Omit<TaskDefinition, 'id' | 'level' | 'points' | 'procedural' | 'reviewStatus'>

const makeTask = (number: number, definition: LevelFiveInput): TaskDefinition => ({
  ...definition,
  id: `L5-${String(number).padStart(3, '0')}`,
  level: 5,
  points: 180,
  procedural: false,
  reviewStatus: 'verified',
})

const materialsRule = 'Вывод о строительном материале связывают с его составом, структурой и условиями эксплуатации.'

export const level5Tasks: readonly TaskDefinition[] = [
  makeTask(161, {
    topic: 'Строительные материалы', subtopic: 'Бетон', difficulty: 1,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Какое минеральное вяжущее является основой обычного цементного бетона?',
    correctAnswer: 'цемент', options: ['цемент', 'кварцевый песок', 'стальная арматура', 'вода'],
    explanation: 'Цемент при взаимодействии с водой образует продукты гидратации, которые связывают заполнители в монолит.',
    rule: 'Цемент является гидравлическим минеральным вяжущим.', example: 'Портландцемент широко используют в обычном бетоне.',
    hint: 'Выбери компонент, который выполняет роль вяжущего.', tags: ['construction-materials', 'cement', 'concrete'],
  }),
  makeTask(162, {
    topic: 'Строительные материалы', subtopic: 'Состав бетона', difficulty: 1,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Выбери полный базовый состав обычного цементного бетона.',
    correctAnswer: 'цемент, вода, мелкий и крупный заполнители',
    options: ['цемент, вода, мелкий и крупный заполнители', 'только цемент и вода', 'известь и гипс без заполнителей', 'сталь, стекло и полимер'],
    explanation: 'Обычный бетон включает цементное вяжущее, воду затворения, мелкий и крупный заполнители; специальные добавки вводят по необходимости.',
    rule: materialsRule, example: 'Песок служит мелким, щебень — крупным заполнителем.',
    hint: 'В составе нужны вяжущее, вода и заполнители двух фракций.', tags: ['construction-materials', 'concrete', 'composition'],
  }),
  makeTask(163, {
    topic: 'Химия цемента', subtopic: 'Гидратация', difficulty: 1,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Как называется общий процесс взаимодействия цементных минералов с водой?',
    correctAnswer: 'гидратация', options: ['гидратация', 'карбонизация', 'коррозия', 'пиролиз'],
    explanation: 'Гидратация охватывает химические реакции цементных минералов с водой и образование гидратных продуктов.',
    rule: 'Гидратация начинается после смешивания цемента с водой.', example: 'Продукты гидратации формируют структуру цементного камня.',
    hint: 'Название связано с присоединением и участием воды.', tags: ['cement', 'hydration', 'binder'],
  }),
  makeTask(164, {
    topic: 'Химия цемента', subtopic: 'Твердение', difficulty: 2,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Почему цементный материал постепенно твердеет после смешивания с водой?',
    correctAnswer: 'из-за гидратации цементных минералов и образования продуктов твердения',
    options: ['из-за гидратации цементных минералов и образования продуктов твердения', 'только из-за испарения всей воды', 'из-за плавления заполнителя', 'из-за окисления песка'],
    explanation: 'Химические и физико-химические процессы гидратации создают новые твёрдые фазы и связную структуру цементного камня.',
    rule: materialsRule, example: 'Развитие структуры продолжается после начального схватывания.',
    hint: 'Свяжи воду с реакциями цементных минералов.', tags: ['cement', 'hydration', 'hardening'],
  }),
  makeTask(165, {
    topic: 'Бетон', subtopic: 'Водоцементное отношение', difficulty: 2,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Как чрезмерное увеличение водоцементного отношения обычно влияет на затвердевший бетон?',
    correctAnswer: 'увеличивает пористость и снижает прочность',
    options: ['увеличивает пористость и снижает прочность', 'устраняет все поры и повышает прочность', 'превращает бетон в металл', 'не влияет на структуру'],
    explanation: 'Избыточная вода оставляет после удаления дополнительное поровое пространство, что обычно повышает проницаемость и снижает прочность.',
    rule: 'При сопоставимых условиях рост водоцементного отношения ухудшает плотность структуры.', example: 'Состав с В/Ц 0,70 обычно пористее состава с В/Ц 0,45.',
    hint: 'Представь пространство, которое останется после избытка воды.', tags: ['concrete', 'water-cement-ratio', 'porosity', 'strength'],
  }),
  makeTask(166, {
    topic: 'Известковые материалы', subtopic: 'Оксид кальция', difficulty: 1,
    station: 'formula-board', interactionType: 'formula-builder',
    prompt: 'Собери формулу оксида кальция, используемого в известковом цикле.', correctAnswer: 'CaO',
    parameters: { formulaTokens: ['Ca', 'O'], compound: 'CaO' }, explanation: 'Катион Ca²⁺ и анион O²⁻ соединяются в отношении 1:1, образуя CaO.',
    rule: 'Суммарный заряд формульной единицы равен нулю.', example: 'CaO называют негашёной известью.',
    hint: 'Модули зарядов ионов одинаковы.', tags: ['lime', 'formula', 'calcium-oxide'], constructionContext: 'CaO — промежуточное вещество известкового цикла.',
  }),
  makeTask(167, {
    topic: 'Известковые материалы', subtopic: 'Гашение извести', difficulty: 1,
    station: 'reaction-bench', interactionType: 'equation-completion',
    prompt: 'Закончи уравнение гашения извести: CaO + H₂O → ?', correctAnswer: 'Ca(OH)2', acceptedAnswers: ['Ca(OH)₂'],
    explanation: 'Оксид кальция взаимодействует с водой с образованием гидроксида кальция.',
    rule: 'Основный оксид активного металла с водой образует основание.', example: 'CaO + H₂O → Ca(OH)₂.',
    hint: 'Продукт содержит кальций и две гидроксогруппы.', tags: ['lime', 'hydration', 'reaction'], parameters: { compound: 'CaO' },
  }),
  makeTask(168, {
    topic: 'Известковые материалы', subtopic: 'Карбонизация извести', difficulty: 2,
    station: 'reaction-bench', interactionType: 'equation-completion',
    prompt: 'Закончи уравнение: Ca(OH)₂ + CO₂ → ?', correctAnswer: 'CaCO3 + H2O', acceptedAnswers: ['CaCO₃ + H₂O'],
    explanation: 'Гидроксид кальция связывает углекислый газ с образованием карбоната кальция и воды.',
    rule: 'Основание и кислотный оксид могут образовывать соль и воду.', example: 'Эта реакция замыкает известковый цикл.',
    hint: 'Продукт соли содержит карбонат-ион.', tags: ['lime', 'carbonation', 'reaction'], parameters: { compound: 'Ca(OH)2' },
  }),
  makeTask(169, {
    topic: 'Гипсовые материалы', subtopic: 'Природный гипс', difficulty: 1,
    station: 'substance-storage', interactionType: 'formula-builder',
    prompt: 'Укажи формулу природного двуводного гипса.', correctAnswer: 'CaSO4·2H2O', acceptedAnswers: ['CaSO₄·2H₂O', 'CaSO4*2H2O'],
    parameters: { formulaTokens: ['Ca', 'SO4', '·', '2H2O'], compound: 'CaSO4·2H2O' },
    explanation: 'Природный гипс является дигидратом сульфата кальция и содержит две молекулы кристаллизационной воды.',
    rule: 'Точка в формуле отделяет соль от кристаллизационной воды.', example: 'CaSO₄·2H₂O — дигидрат сульфата кальция.',
    hint: 'Добавь две молекулы воды к CaSO₄.', tags: ['gypsum', 'hydrate', 'formula'],
  }),
  makeTask(170, {
    topic: 'Карбонатные материалы', subtopic: 'Известняк', difficulty: 1,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Какое соединение является основным компонентом известняка?', correctAnswer: 'CaCO3', acceptedAnswers: ['CaCO₃', 'карбонат кальция'],
    options: ['CaCO₃', 'CaO', 'Ca(OH)₂', 'CaSO₄·2H₂O'], explanation: 'Известняк преимущественно состоит из минерала кальцита — карбоната кальция CaCO₃.',
    rule: materialsRule, example: 'При обжиге CaCO₃ образуется CaO.',
    hint: 'Ищи карбонат кальция.', tags: ['limestone', 'carbonate', 'construction-materials'], parameters: { compound: 'CaCO3' },
  }),
  makeTask(171, {
    topic: 'Известковые материалы', subtopic: 'Обжиг известняка', difficulty: 1,
    station: 'reaction-bench', interactionType: 'equation-completion',
    prompt: 'Закончи уравнение обжига известняка: CaCO₃ → ?', correctAnswer: 'CaO + CO2', acceptedAnswers: ['CaO + CO₂'],
    explanation: 'При нагревании карбонат кальция разлагается на оксид кальция и углекислый газ.',
    rule: 'Термическое разложение CaCO₃: CaCO₃ → CaO + CO₂.', example: 'Процесс является стадией получения извести.',
    hint: 'Образуются оксид кальция и газ.', tags: ['limestone', 'lime', 'decomposition'], parameters: { compound: 'CaCO3' },
  }),
  makeTask(172, {
    topic: 'Известковые материалы', subtopic: 'Известковый цикл', difficulty: 2,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Выбери правильную последовательность веществ известкового цикла.',
    correctAnswer: 'CaCO₃ → CaO → Ca(OH)₂ → CaCO₃', acceptedAnswers: ['CaCO3 → CaO → Ca(OH)2 → CaCO3'],
    options: ['CaCO₃ → CaO → Ca(OH)₂ → CaCO₃', 'CaO → CaCO₃ → Ca(OH)₂ → CaO', 'Ca(OH)₂ → CaO → CaCO₃ → H₂O', 'CaCO₃ → Ca(OH)₂ → CaO → CO₂'],
    explanation: 'Известняк обжигают до CaO, гашением получают Ca(OH)₂, а карбонизация возвращает CaCO₃.',
    rule: 'Цикл объединяет обжиг, гашение и карбонизацию.', example: 'Ca(OH)₂ + CO₂ → CaCO₃ + H₂O.',
    hint: 'Начни с известняка и найди стадии обжига и гашения.', tags: ['lime', 'sequence', 'carbonation'],
  }),
  makeTask(173, {
    topic: 'Известковые материалы', subtopic: 'Обжиг известняка', difficulty: 1,
    station: 'reaction-bench', interactionType: 'construction-material',
    prompt: 'Какой тип реакции происходит при обжиге CaCO₃?', correctAnswer: 'термическое разложение',
    options: ['термическое разложение', 'нейтрализация', 'замещение', 'полимеризация'],
    explanation: 'Одно сложное вещество при нагревании образует два продукта: CaO и CO₂.',
    rule: 'При разложении из одного реагента образуется несколько продуктов.', example: 'CaCO₃ → CaO + CO₂.',
    hint: 'Посчитай число исходных веществ и продуктов.', tags: ['lime', 'reaction-type', 'decomposition'], parameters: { compound: 'CaCO3' },
  }),
  makeTask(174, {
    topic: 'Строительные материалы', subtopic: 'Минеральные вяжущие', difficulty: 2,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Сопоставь материал с игровой категорией: цемент, гипс и воздушная известь.',
    correctAnswer: 'цемент — гидравлическое; гипс — воздушное; воздушная известь — воздушное',
    options: ['цемент — гидравлическое; гипс — воздушное; воздушная известь — воздушное', 'все три — металлические', 'цемент — воздушное; гипс — гидравлическое; известь — полимерное', 'все три — заполнители'],
    explanation: 'Портландцемент способен твердеть и сохранять прочность в воде; гипсовое и воздушно-известковое вяжущие относят к воздушным.',
    rule: 'Категория вяжущего определяется условиями твердения и сохранения прочности.', example: 'Цемент используют для бетона во влажных условиях.',
    hint: 'Отдели гидравлическое вяжущее от воздушных.', tags: ['binders', 'cement', 'gypsum', 'lime'],
  }),
  makeTask(175, {
    topic: 'Силикаты', subtopic: 'Степень окисления', difficulty: 1,
    station: 'formula-board', interactionType: 'oxidation-state',
    prompt: 'Определи степень окисления кремния в SiO₂.', correctAnswer: '+4', acceptedAnswers: ['4+'],
    options: ['+4', '+2', '−4', '0'], explanation: 'Два атома кислорода дают суммарно −4, поэтому кремний в нейтральном SiO₂ имеет степень окисления +4.',
    rule: 'Сумма степеней окисления в нейтральном соединении равна нулю.', example: '+4 + 2·(−2) = 0.',
    hint: 'Кислород обычно имеет степень окисления −2.', tags: ['silicates', 'oxidation-state', 'silicon'], parameters: { compound: 'SiO2' },
  }),
  makeTask(176, {
    topic: 'Химия воды', subtopic: 'Временная жёсткость', difficulty: 2,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Какие соли преимущественно вызывают временную жёсткость воды?',
    correctAnswer: 'гидрокарбонаты кальция и магния',
    options: ['гидрокарбонаты кальция и магния', 'нитраты натрия и калия', 'хлориды натрия и калия', 'сульфаты алюминия и железа'],
    explanation: 'Карбонатная временная жёсткость связана главным образом с растворёнными гидрокарбонатами Ca(HCO₃)₂ и Mg(HCO₃)₂.',
    rule: 'Временную жёсткость также называют карбонатной.', example: 'Ca(HCO₃)₂ содержит ион жёсткости Ca²⁺.',
    hint: 'Выбери соли с гидрокарбонат-ионом.', tags: ['water', 'hardness', 'bicarbonate'],
  }),
  makeTask(177, {
    topic: 'Химия воды', subtopic: 'Постоянная жёсткость', difficulty: 2,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Какие соли могут формировать постоянную жёсткость воды?',
    correctAnswer: 'сульфаты и хлориды кальция и магния',
    options: ['сульфаты и хлориды кальция и магния', 'только гидрокарбонат натрия', 'нитрат калия и сахароза', 'карбонат натрия и гидроксид калия'],
    explanation: 'Некарбонатная постоянная жёсткость связана, например, с сульфатами и хлоридами Ca²⁺ и Mg²⁺.',
    rule: 'Жёсткость определяют прежде всего ионы Ca²⁺ и Mg²⁺.', example: 'CaSO₄ и MgCl₂ вносят вклад в постоянную жёсткость.',
    hint: 'Ищи соли кальция и магния без гидрокарбоната.', tags: ['water', 'hardness', 'sulfate', 'chloride'],
  }),
  makeTask(178, {
    topic: 'Химия воды', subtopic: 'Ионы жёсткости', difficulty: 1,
    station: 'construction-materials-station', interactionType: 'ion-builder',
    prompt: 'Выбери два основных катиона жёсткости воды.', correctAnswer: 'Ca^2+ и Mg^2+',
    acceptedAnswers: ['Ca²⁺ и Mg²⁺', 'Mg^2+ и Ca^2+', 'Mg²⁺ и Ca²⁺'],
    options: ['Ca²⁺ и Mg²⁺', 'Na⁺ и K⁺', 'H⁺ и NH₄⁺', 'Al³⁺ и Fe³⁺'],
    explanation: 'Общую жёсткость природной воды в основной учебной модели определяют концентрации Ca²⁺ и Mg²⁺.',
    rule: 'Кальций и магний являются главными ионами жёсткости.', example: 'Их суммарное содержание используют при сравнении проб.',
    hint: 'Это щёлочноземельные металлы второй группы.', tags: ['water', 'hardness', 'calcium', 'magnesium'],
  }),
  makeTask(179, {
    topic: 'Химия воды', subtopic: 'Карбонатная накипь', difficulty: 1,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Какое соединение часто является важным компонентом карбонатной накипи?',
    correctAnswer: 'CaCO3', acceptedAnswers: ['CaCO₃', 'карбонат кальция'],
    options: ['CaCO₃', 'NaCl', 'KNO₃', 'CO₂'], explanation: 'Карбонат кальция малорастворим и может выделяться в твёрдую фазу при изменении состава и нагревании воды.',
    rule: 'Карбонатная накипь часто содержит CaCO₃.', example: 'CaCO₃ также является главным компонентом известняка.',
    hint: 'Выбери малорастворимый карбонат кальция.', tags: ['water', 'scale', 'carbonate'], parameters: { compound: 'CaCO3' },
  }),
  makeTask(180, {
    topic: 'Химия воды', subtopic: 'Сравнение жёсткости', difficulty: 2,
    station: 'construction-materials-station', interactionType: 'construction-mission',
    prompt: 'Проба A: Ca²⁺ = 2.0 mmol/L, Mg²⁺ = 0.5 mmol/L. Проба B: Ca²⁺ = 1.0 mmol/L, Mg²⁺ = 1.0 mmol/L. Какая проба жёстче по сумме концентраций?',
    correctAnswer: 'проба A', acceptedAnswers: ['A'], options: ['проба A', 'проба B', 'одинаковая жёсткость', 'данных о pH достаточно'],
    explanation: 'Сумма для A равна 2.5 mmol/L, для B — 2.0 mmol/L, поэтому в заданной модели проба A жёстче.',
    rule: 'При одинаковых единицах сравнивают суммарную концентрацию Ca²⁺ и Mg²⁺.', example: '2.0 + 0.5 = 2.5 mmol/L.',
    hint: 'Сложи две концентрации для каждой пробы.', tags: ['water', 'hardness', 'calculation', 'mission'],
    parameters: { missionSteps: [
      { title: 'Проба A', readout: 'Ca²⁺ 2.0 · Mg²⁺ 0.5 mmol/L' },
      { title: 'Проба B', readout: 'Ca²⁺ 1.0 · Mg²⁺ 1.0 mmol/L' },
      { title: 'Сравнение', readout: 'Σ(Ca²⁺ + Mg²⁺)' },
    ] },
  }),
  makeTask(181, {
    topic: 'Железобетон', subtopic: 'Пассивация арматуры', difficulty: 2,
    station: 'corrosion-test-rig', interactionType: 'corrosion-inspection',
    prompt: 'Почему высокая щёлочность нормального цементного бетона может защищать стальную арматуру?',
    correctAnswer: 'способствует образованию и сохранению пассивного состояния стали',
    options: ['способствует образованию и сохранению пассивного состояния стали', 'полностью удаляет железо из арматуры', 'растворяет защитный слой бетона', 'заменяет сталь полимером'],
    explanation: 'Высокий pH поровой жидкости поддерживает на стали защитную пассивную плёнку и снижает скорость коррозии.',
    rule: 'Щелочная среда бетона является важным фактором пассивности арматуры.', example: 'Снижение pH у поверхности стали повышает риск депассивации.',
    hint: 'Свяжи высокий pH с защитной плёнкой.', tags: ['reinforcement', 'passivation', 'alkalinity', 'concrete'],
  }),
  makeTask(182, {
    topic: 'Карбонизация бетона', subtopic: 'Реагент', difficulty: 1,
    station: 'corrosion-test-rig', interactionType: 'corrosion-inspection',
    prompt: 'Какой газ участвует в карбонизации бетона?', correctAnswer: 'CO2', acceptedAnswers: ['CO₂', 'углекислый газ'],
    options: ['CO₂', 'O₂', 'H₂', 'N₂'], explanation: 'Углекислый газ проникает в поры и реагирует с щелочными компонентами цементного камня.',
    rule: 'Карбонизация связана с воздействием атмосферного CO₂.', example: 'CO₂ может реагировать с Ca(OH)₂ с образованием CaCO₃.',
    hint: 'Название процесса связано с углеродом.', tags: ['concrete', 'carbonation', 'carbon-dioxide'], parameters: { compound: 'CO2' },
  }),
  makeTask(183, {
    topic: 'Карбонизация бетона', subtopic: 'Изменение pH', difficulty: 2,
    station: 'corrosion-test-rig', interactionType: 'corrosion-inspection',
    prompt: 'Как карбонизация обычно влияет на pH цементного бетона?', correctAnswer: 'снижает pH', acceptedAnswers: ['снижает'],
    options: ['снижает pH', 'повышает pH до максимума', 'всегда сохраняет pH без изменений', 'делает pH отрицательным'],
    explanation: 'Карбонизация расходует щелочные компоненты цементного камня, поэтому щёлочность и pH снижаются.',
    rule: 'Продвижение фронта карбонизации уменьшает защитную щёлочность.', example: 'У арматуры это может привести к потере пассивации.',
    hint: 'Щелочные компоненты вступают в реакцию с CO₂.', tags: ['concrete', 'carbonation', 'pH'],
  }),
  makeTask(184, {
    topic: 'Железобетон', subtopic: 'Карбонизация и арматура', difficulty: 3,
    station: 'corrosion-test-rig', interactionType: 'corrosion-inspection',
    prompt: 'Чем опасно продвижение фронта карбонизации к арматуре?',
    correctAnswer: 'снижение щёлочности может нарушить пассивность стали и повысить риск коррозии',
    options: ['снижение щёлочности может нарушить пассивность стали и повысить риск коррозии', 'арматура превращается в заполнитель', 'бетон автоматически становится водонепроницаемым', 'CO₂ повышает pH у стали'],
    explanation: 'Когда карбонизированная зона достигает арматуры, пониженный pH может дестабилизировать защитную плёнку стали.',
    rule: 'Глубину карбонизации сопоставляют с толщиной защитного слоя.', example: 'Депассивация создаёт условия для коррозии при наличии влаги и кислорода.',
    hint: 'Оцени влияние пониженного pH на защитную плёнку.', tags: ['reinforcement', 'carbonation', 'corrosion', 'passivation'],
  }),
  makeTask(185, {
    topic: 'Железобетон', subtopic: 'Хлоридное воздействие', difficulty: 3,
    station: 'corrosion-test-rig', interactionType: 'corrosion-inspection',
    prompt: 'Почему хлорид-ионы опасны для железобетона?',
    correctAnswer: 'могут нарушать пассивность стали и способствовать локальной коррозии',
    options: ['могут нарушать пассивность стали и способствовать локальной коррозии', 'всегда повышают прочность стали', 'полностью блокируют перенос ионов', 'превращают бетон в стекло'],
    explanation: 'При достаточном содержании у поверхности арматуры хлориды способны локально разрушать пассивное состояние и инициировать питтинговую коррозию.',
    rule: 'Риск зависит от содержания хлоридов у арматуры и условий эксплуатации.', example: 'Морская среда требует контроля проникновения Cl⁻.',
    hint: 'Подумай о локальном разрушении пассивной плёнки.', tags: ['reinforcement', 'chloride', 'corrosion', 'passivation'],
  }),
  makeTask(186, {
    topic: 'Инспекция конструкций', subtopic: 'Признаки коррозии', difficulty: 2,
    station: 'inspection-station', interactionType: 'construction-mission',
    prompt: 'На железобетоне обнаружены продольные трещины и ржавые пятна. Что следует проверить в первую очередь?',
    correctAnswer: 'состояние арматуры и возможную коррозию',
    options: ['состояние арматуры и возможную коррозию', 'только цвет заполнителя', 'электронную конфигурацию кремния', 'температуру плавления цемента'],
    explanation: 'Трещины вдоль арматуры и ржавые пятна являются основанием для обследования стали, защитного слоя и условий коррозии.',
    rule: 'Диагноз подтверждают совокупностью наблюдений и измерений.', example: 'Дополнительно оценивают pH, хлориды и влажность.',
    hint: 'Свяжи ржавые следы с металлическим элементом внутри бетона.', tags: ['inspection', 'reinforcement', 'corrosion', 'cracks'],
    parameters: { missionSteps: [
      { title: 'Визуальный осмотр', readout: 'Продольные трещины · ржавые пятна' },
      { title: 'Локализация', readout: 'Следы совпадают с линией арматуры' },
      { title: 'Решение', readout: 'Назначить обследование стали' },
    ] },
  }),
  makeTask(187, {
    topic: 'Железобетон', subtopic: 'pH у арматуры', difficulty: 2,
    station: 'corrosion-test-rig', interactionType: 'corrosion-inspection',
    prompt: 'Вблизи арматуры измерен значительно пониженный pH. Какой риск возрастает?',
    correctAnswer: 'потеря пассивации и последующая коррозия стали',
    options: ['потеря пассивации и последующая коррозия стали', 'мгновенное увеличение диаметра арматуры', 'переход стали в полимер', 'образование нейтронов'],
    explanation: 'Снижение щёлочности может дестабилизировать пассивную плёнку; при наличии воды и кислорода возрастает риск коррозии.',
    rule: 'pH у арматуры является одним из индикаторов условий пассивности.', example: 'Карбонизация способна снижать pH защитного слоя.',
    hint: 'Оцени устойчивость защитной плёнки при меньшей щёлочности.', tags: ['reinforcement', 'pH', 'passivation', 'corrosion'],
  }),
  makeTask(188, {
    topic: 'Железобетон', subtopic: 'Хлориды у арматуры', difficulty: 2,
    station: 'corrosion-test-rig', interactionType: 'corrosion-inspection',
    prompt: 'Около арматуры обнаружено повышенное содержание Cl⁻. Какой риск это создаёт?',
    correctAnswer: 'нарушение пассивности и локальная коррозия арматуры',
    options: ['нарушение пассивности и локальная коррозия арматуры', 'полное исключение электрохимических процессов', 'увеличение pH без ограничений', 'образование гипса внутри стали'],
    explanation: 'Хлориды у поверхности стали могут локально нарушать пассивную плёнку и инициировать интенсивные коррозионные очаги.',
    rule: 'Контролируют содержание Cl⁻ именно в зоне арматуры.', example: 'Особое внимание требуется в солесодержащей среде.',
    hint: 'Хлориды опасны для локальной устойчивости пассивной плёнки.', tags: ['reinforcement', 'chloride', 'corrosion'],
  }),
  makeTask(189, {
    topic: 'Защита бетона', subtopic: 'Проницаемость', difficulty: 2,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Какой общий принцип уменьшает проникновение воды и агрессивных веществ в бетон?',
    correctAnswer: 'снижение проницаемости и применение подходящей защитной системы',
    options: ['снижение проницаемости и применение подходящей защитной системы', 'увеличение открытой пористости', 'создание дополнительных трещин', 'добавление растворимых солей на поверхность'],
    explanation: 'Плотная структура и правильно выбранная защитная система замедляют транспорт воды, газов и растворённых ионов.',
    rule: materialsRule, example: 'Качественный защитный слой снижает скорость проникновения среды.',
    hint: 'Нужно затруднить транспорт веществ через поры.', tags: ['concrete', 'protection', 'permeability'],
  }),
  makeTask(190, {
    topic: 'Инспекция конструкций', subtopic: 'Источник проблемы', difficulty: 3,
    station: 'inspection-station', interactionType: 'construction-mission',
    prompt: 'Проба воды имеет высокие Ca²⁺ и Mg²⁺, а на трубопроводе обнаружена карбонатная накипь. Выбери основной источник проблемы.',
    correctAnswer: 'строительная вода', acceptedAnswers: ['вода'],
    options: ['строительная вода', 'полимерный герметик', 'стальная арматура', 'кварцевый заполнитель'],
    explanation: 'Повышенное содержание ионов жёсткости в воде согласуется с образованием карбонатных отложений в водном контуре.',
    rule: 'Источник диагностируют по согласованной цепочке измерение → процесс → проявление.', example: 'Ca²⁺ и Mg²⁺ являются главными ионами жёсткости.',
    hint: 'Сопоставь химический анализ пробы и тип отложений.', tags: ['inspection', 'water', 'hardness', 'scale'],
    parameters: { missionSteps: [
      { title: 'Отбор пробы', readout: 'Вода из строительного контура' },
      { title: 'Ионный анализ', readout: 'Повышены Ca²⁺ и Mg²⁺' },
      { title: 'Осмотр', readout: 'Карбонатная накипь на трубе' },
    ] },
  }),
  makeTask(191, {
    topic: 'Агрессивные среды', subtopic: 'Кислотное воздействие', difficulty: 2,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Как кислая среда может влиять на цементный камень?',
    correctAnswer: 'реагирует с компонентами цементного камня и вызывает постепенное разрушение',
    options: ['реагирует с компонентами цементного камня и вызывает постепенное разрушение', 'всегда повышает щёлочность', 'превращает цемент в сталь', 'полностью закрывает все поры'],
    explanation: 'Кислоты нейтрализуют и растворяют щелочные компоненты цементного камня, ослабляя его структуру.',
    rule: 'Кислотостойкость обычного цементного камня ограничена.', example: 'Воздействие оценивают по составу, концентрации и длительности.',
    hint: 'Учти кислотно-основное взаимодействие со щелочными компонентами.', tags: ['aggressive-environment', 'acid', 'cement'],
  }),
  makeTask(192, {
    topic: 'Агрессивные среды', subtopic: 'Сульфатное воздействие', difficulty: 3,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Почему сульфатсодержащие среды важны для строительной химии?',
    correctAnswer: 'могут вызывать химические превращения, расширяющиеся продукты и повреждение цементных материалов',
    options: ['могут вызывать химические превращения, расширяющиеся продукты и повреждение цементных материалов', 'всегда повышают прочность любого бетона', 'не взаимодействуют с цементным камнем', 'заменяют заполнитель металлом'],
    explanation: 'Некоторые виды сульфатного воздействия приводят к образованию фаз с увеличенным объёмом и внутренним напряжениям.',
    rule: 'Опасность зависит от состава цемента, проницаемости и условий среды.', example: 'Повреждение может проявляться расширением и трещинами.',
    hint: 'Подумай о новых твёрдых фазах и изменении объёма.', tags: ['aggressive-environment', 'sulfate', 'cement', 'expansion'],
  }),
  makeTask(193, {
    topic: 'Агрессивные среды', subtopic: 'Морская среда', difficulty: 3,
    station: 'inspection-station', interactionType: 'construction-mission',
    prompt: 'Что необходимо контролировать при эксплуатации железобетона в солесодержащей морской среде?',
    correctAnswer: 'ионы, защитный слой, арматуру и признаки коррозии',
    options: ['ионы, защитный слой, арматуру и признаки коррозии', 'только цвет поверхности', 'только температуру воздуха один раз', 'только марку заполнителя'],
    explanation: 'Надёжная оценка объединяет проникновение агрессивных ионов, состояние защитного слоя бетона, арматуры и внешние признаки повреждения.',
    rule: 'Инспекция агрессивной среды использует несколько взаимосвязанных показателей.', example: 'Содержание Cl⁻ сопоставляют с глубиной арматуры.',
    hint: 'Выбери комплексный контроль среды и конструкции.', tags: ['marine', 'chloride', 'inspection', 'reinforcement'],
    parameters: { missionSteps: [
      { title: 'Среда', readout: 'Солесодержащая вода · циклы увлажнения' },
      { title: 'Защитный слой', readout: 'Проверить толщину и трещины' },
      { title: 'Арматура', readout: 'Cl⁻ · потенциал · следы коррозии' },
    ] },
  }),
  makeTask(194, {
    topic: 'Бетон', subtopic: 'Пористость', difficulty: 1,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Как высокая открытая пористость обычно влияет на проникновение воды и растворённых веществ в бетон?',
    correctAnswer: 'облегчает проникновение', options: ['облегчает проникновение', 'полностью блокирует проникновение', 'не влияет на транспорт', 'превращает воду в газ'],
    explanation: 'Связанная система открытых пор создаёт пути для капиллярного всасывания и переноса растворённых веществ.',
    rule: 'Проницаемость связана с объёмом, размером и связностью пор.', example: 'Более плотная структура обычно замедляет транспорт воды.',
    hint: 'Представь связанную сеть каналов внутри материала.', tags: ['concrete', 'porosity', 'permeability'],
  }),
  makeTask(195, {
    topic: 'Полимерные материалы', subtopic: 'Применение', difficulty: 2,
    station: 'construction-materials-station', interactionType: 'construction-material',
    prompt: 'Для чего применяют полимерные материалы и добавки в строительстве?',
    correctAnswer: 'для направленного изменения требуемых свойств и защиты материалов',
    options: ['для направленного изменения требуемых свойств и защиты материалов', 'только для увеличения плотности стали', 'для превращения цемента в элемент', 'исключительно как крупный заполнитель'],
    explanation: 'Полимеры применяют для регулирования адгезии, водостойкости, деформативности, герметичности и защитных характеристик.',
    rule: 'Конкретный эффект определяется типом полимера и системой материала.', example: 'Полимерные покрытия могут выполнять барьерную функцию.',
    hint: 'Ищи ответ с несколькими управляемыми свойствами.', tags: ['polymers', 'construction-materials', 'protection'],
  }),
  makeTask(196, {
    topic: 'Химия воды', subtopic: 'Оценка строительной воды', difficulty: 3,
    station: 'inspection-station', interactionType: 'construction-mission',
    prompt: 'Проба содержит Ca²⁺ = 1.8 mmol/L и Mg²⁺ = 1.2 mmol/L. Определи суммарную концентрацию ионов жёсткости.',
    correctAnswer: { value: 3, absoluteTolerance: 0.05, unit: 'mmol/L' },
    explanation: 'В заданной модели суммарная концентрация ионов жёсткости равна 1.8 + 1.2 = 3.0 mmol/L.',
    rule: 'При одинаковых единицах складывают концентрации Ca²⁺ и Mg²⁺.', example: '2.0 + 0.5 = 2.5 mmol/L.',
    hint: 'Сложи показания двух ионных каналов.', tags: ['mission', 'water', 'hardness', 'calculation'],
    parameters: { missionSteps: [
      { title: 'Отбор', readout: 'Проба W-16 принята' },
      { title: 'Кальций', readout: 'Ca²⁺ = 1.8 mmol/L' },
      { title: 'Магний', readout: 'Mg²⁺ = 1.2 mmol/L' },
      { title: 'Оценка', readout: 'Рассчитать сумму' },
    ] }, constructionContext: 'Виртуальная оценка воды для строительного контура.',
  }),
  makeTask(197, {
    topic: 'Железобетон', subtopic: 'Комплексная инспекция', difficulty: 4,
    station: 'inspection-station', interactionType: 'construction-mission',
    prompt: 'У арматуры pH = 9.2, обнаружены Cl⁻ и высокая влажность. Выбери итоговую оценку.',
    correctAnswer: 'высокий риск депассивации и электрохимической коррозии арматуры',
    options: ['высокий риск депассивации и электрохимической коррозии арматуры', 'арматура надёжно защищена при любых условиях', 'происходит только гидратация цемента', 'хлориды устраняют влияние влажности'],
    explanation: 'Пониженная щёлочность, хлориды и влага совместно создают неблагоприятные условия для пассивности и коррозионной стойкости стали.',
    rule: 'Риск оценивают по совокупности pH, хлоридов, влаги и состояния бетона.', example: 'Защитное решение выбирают после подтверждённой диагностики.',
    hint: 'Объедини три неблагоприятных показателя.', tags: ['mission', 'reinforcement', 'pH', 'chloride', 'corrosion'],
    parameters: { missionSteps: [
      { title: 'Осмотр', readout: 'Трещины вдоль арматуры' },
      { title: 'pH-скан', readout: 'pH = 9.2 у стали' },
      { title: 'Хлориды', readout: 'Cl⁻ обнаружены' },
      { title: 'Влажность', readout: 'Высокая' },
      { title: 'Диагноз', readout: 'Оценить коррозионный риск' },
    ] }, constructionContext: 'Виртуальное обследование железобетонного элемента.',
  }),
  makeTask(198, {
    topic: 'Бетон', subtopic: 'Сравнение составов', difficulty: 3,
    station: 'construction-materials-station', interactionType: 'construction-mission',
    prompt: 'Состав A имеет В/Ц = 0.45, состав B — В/Ц = 0.70. При сопоставимых материалах какой состав обычно плотнее и прочнее после твердения?',
    correctAnswer: 'состав A', acceptedAnswers: ['A'], options: ['состав A', 'состав B', 'характеристики всегда одинаковы', 'В/Ц не связано с пористостью'],
    explanation: 'Меньшее водоцементное отношение при корректном уплотнении обычно оставляет меньше капиллярных пор и обеспечивает более высокую прочность.',
    rule: 'Сравнение справедливо при сопоставимых материалах, уходе и достаточной удобоукладываемости.', example: 'В/Ц 0.45 обычно даёт более плотную структуру, чем 0.70.',
    hint: 'Сопоставь избыток воды с будущей пористостью.', tags: ['mission', 'concrete', 'water-cement-ratio', 'strength'],
    parameters: { missionSteps: [
      { title: 'Состав A', readout: 'В/Ц = 0.45' },
      { title: 'Состав B', readout: 'В/Ц = 0.70' },
      { title: 'Прогноз пористости', readout: 'Избыток воды → дополнительные поры' },
      { title: 'Выбор', readout: 'Нужна более плотная структура' },
    ] },
  }),
  makeTask(199, {
    topic: 'Известковые материалы', subtopic: 'Идентификация веществ', difficulty: 3,
    station: 'construction-materials-station', interactionType: 'construction-mission',
    prompt: 'Сопоставь три образца известкового цикла с названиями.',
    correctAnswer: 'CaO — оксид кальция; Ca(OH)2 — гидроксид кальция; CaCO3 — карбонат кальция',
    options: ['CaO — оксид кальция; Ca(OH)₂ — гидроксид кальция; CaCO₃ — карбонат кальция', 'CaO — карбонат; Ca(OH)₂ — оксид; CaCO₃ — гидроксид', 'все три — сульфаты кальция', 'все три — формы металлического кальция'],
    explanation: 'CaO является оксидом, Ca(OH)₂ — основанием, а CaCO₃ — солью угольной кислоты.',
    rule: 'Формула определяет класс и систематическое название вещества.', example: 'Обжиг, гашение и карбонизация связывают эти три соединения.',
    hint: 'Различи O²⁻, OH⁻ и CO₃²⁻.', tags: ['mission', 'lime', 'nomenclature', 'formula'],
    parameters: { missionSteps: [
      { title: 'Образец A', readout: 'CaO · продукт обжига' },
      { title: 'Образец B', readout: 'Ca(OH)₂ · продукт гашения' },
      { title: 'Образец C', readout: 'CaCO₃ · продукт карбонизации' },
    ] },
  }),
  makeTask(200, {
    topic: 'Строительная химия', subtopic: 'Итоговая инспекция', difficulty: 5,
    station: 'inspection-station', interactionType: 'construction-mission',
    prompt: 'Финальная инспекция: выбери последовательность, связывающую формулу, реакцию, раствор, коррозию и строительный вывод.',
    correctAnswer: 'CaCO₃ → CaO + CO₂; pH снижен; Fe окисляется; защиту восстановить',
    acceptedAnswers: ['CaCO3 → CaO + CO2; pH снижен; Fe окисляется; защиту восстановить'],
    options: [
      'CaCO₃ → CaO + CO₂; pH снижен; Fe окисляется; защиту восстановить',
      'CaCO₃ → Ca + CO₃; pH повышен; Fe восстанавливается; добавить хлориды',
      'CaO → CaCO₃ + O₂; pH не измерять; Fe плавится; увеличить пористость',
      'CaCO₃ не реагирует; вода не влияет; коррозия невозможна; снять покрытие',
    ],
    explanation: 'Проверенная цепочка объединяет разложение карбоната, потерю щёлочности у стали, анодное окисление железа и восстановление защитного барьера.',
    rule: 'Итоговая миссия связывает данные предыдущих уровней в единую инженерную причинную цепь.',
    example: 'Fe → Fe²⁺ + 2e⁻ является анодной стадией коррозии.',
    hint: 'Проверь каждую часть цепочки отдельно: уравнение, pH, электродный процесс, защита.',
    tags: ['final-mission', 'adaptive', 'reaction', 'pH', 'corrosion', 'construction'],
    parameters: { missionSteps: [
      { title: 'Формула', readout: 'Известняк: CaCO₃' },
      { title: 'Реакция', readout: 'Обжиг: CaCO₃ → CaO + CO₂' },
      { title: 'Раствор', readout: 'pH у арматуры снижен' },
      { title: 'Электрохимия', readout: 'Fe → Fe²⁺ + 2e⁻' },
      { title: 'Инспекция', readout: 'Покрытие повреждено' },
    ] }, constructionContext: 'Финальная виртуальная приёмка химической безопасности участка.',
  }),
] as const
