import type { TaskDefinition } from '../types'

type LevelThreeInput = Omit<TaskDefinition, 'id' | 'level' | 'points' | 'procedural' | 'reviewStatus'>

const makeTask = (number: number, definition: LevelThreeInput): TaskDefinition => ({
  ...definition,
  id: `L3-${String(number).padStart(3, '0')}`,
  level: 3,
  points: 140,
  procedural: false,
  reviewStatus: 'verified',
})

const numericHint = 'Запиши формулу, переведи величины в согласованные единицы и подставь данные.'
const concentrationRule = 'Молярная концентрация C = n/V, где V выражен в литрах.'

export const level3Tasks: readonly TaskDefinition[] = [
  makeTask(81, { topic: 'Количество вещества', subtopic: 'Молярная масса', difficulty: 1, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: 'Рассчитай молярную массу H₂O в g/mol.', correctAnswer: { value: 18.02, absoluteTolerance: 0.05, unit: 'g/mol' }, explanation: 'M(H₂O) = 2·1.008 + 16.00 = 18.016 g/mol.', rule: 'Молярная масса равна сумме атомных масс с учётом индексов.', example: 'M(O₂) = 32.00 g/mol.', hint: 'Сложи массы двух H и одного O.', tags: ['molar-mass', 'water'], parameters: { compound: 'H2O' } }),
  makeTask(82, { topic: 'Количество вещества', subtopic: 'Молярная масса', difficulty: 1, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: 'Рассчитай молярную массу NaOH в g/mol.', correctAnswer: { value: 40, absoluteTolerance: 0.05, unit: 'g/mol' }, explanation: 'M(NaOH) = 22.99 + 16.00 + 1.008 ≈ 40.00 g/mol.', rule: 'Суммируй атомные массы всех атомов формулы.', example: 'M(KOH) ≈ 56.11 g/mol.', hint: 'Сложи Na, O и H.', tags: ['molar-mass', 'sodium-hydroxide'], parameters: { compound: 'NaOH' } }),
  makeTask(83, { topic: 'Количество вещества', subtopic: 'Молярная масса', difficulty: 1, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: 'Рассчитай молярную массу CaCO₃ в g/mol.', correctAnswer: { value: 100.09, absoluteTolerance: 0.2, unit: 'g/mol' }, explanation: 'M(CaCO₃) = 40.08 + 12.01 + 3·16.00 = 100.09 g/mol.', rule: 'Индекс 3 умножает атомную массу кислорода.', example: '0.10 mol CaCO₃ имеет массу около 10.01 g.', hint: 'Учти три атома кислорода.', tags: ['molar-mass', 'carbonate', 'construction'], parameters: { compound: 'CaCO3' }, constructionContext: 'CaCO₃ — основной компонент известняка.' }),
  makeTask(84, { topic: 'Количество вещества', subtopic: 'Молярная масса', difficulty: 1, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: 'Рассчитай молярную массу H₂SO₄ в g/mol.', correctAnswer: { value: 98.08, absoluteTolerance: 0.2, unit: 'g/mol' }, explanation: 'M(H₂SO₄) = 2·1.008 + 32.06 + 4·16.00 ≈ 98.08 g/mol.', rule: 'Каждый индекс умножает атомную массу соответствующего элемента.', example: 'M(SO₃) ≈ 80.06 g/mol.', hint: 'Учти два H и четыре O.', tags: ['molar-mass', 'sulfuric-acid'], parameters: { compound: 'H2SO4' } }),
  makeTask(85, { topic: 'Количество вещества', subtopic: 'Молярная масса', difficulty: 1, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: 'Рассчитай молярную массу NaCl в g/mol.', correctAnswer: { value: 58.44, absoluteTolerance: 0.1, unit: 'g/mol' }, explanation: 'M(NaCl) = 22.99 + 35.45 = 58.44 g/mol.', rule: 'Для формульной единицы соли складывают массы всех ионов по составу.', example: '0.25 mol NaCl имеет массу около 14.61 g.', hint: 'Сложи атомные массы Na и Cl.', tags: ['molar-mass', 'sodium-chloride'], parameters: { compound: 'NaCl' } }),
  makeTask(86, { topic: 'Количество вещества', subtopic: 'Масса в моли', difficulty: 1, station: 'solution-laboratory', interactionType: 'virtual-scales', prompt: 'Сколько mol содержится в 18.02 g H₂O?', correctAnswer: { value: 1, absoluteTolerance: 0.01, unit: 'mol' }, explanation: 'n = m/M = 18.02/18.02 = 1 mol.', rule: 'Количество вещества n = m/M.', example: '36.04 g H₂O соответствует 2 mol.', hint: numericHint, tags: ['moles', 'mass', 'water'], parameters: { compound: 'H2O', scaleMode: 'mass-to-moles', sampleMass: 18.02, molarMass: 18.02 } }),
  makeTask(87, { topic: 'Количество вещества', subtopic: 'Масса в моли', difficulty: 1, station: 'solution-laboratory', interactionType: 'virtual-scales', prompt: 'Сколько mol содержится в 20 g NaOH?', correctAnswer: { value: 0.5, absoluteTolerance: 0.01, unit: 'mol' }, explanation: 'n = 20/40.00 = 0.50 mol.', rule: 'Количество вещества n = m/M.', example: '40 g NaOH соответствует 1 mol.', hint: 'Используй M(NaOH) = 40.00 g/mol.', tags: ['moles', 'mass', 'sodium-hydroxide'], parameters: { compound: 'NaOH', scaleMode: 'mass-to-moles', sampleMass: 20, molarMass: 40.00 } }),
  makeTask(88, { topic: 'Количество вещества', subtopic: 'Моли в массу', difficulty: 1, station: 'solution-laboratory', interactionType: 'virtual-scales', prompt: 'Найди массу 2 mol CO₂ в граммах.', correctAnswer: { value: 88.02, absoluteTolerance: 0.2, unit: 'g' }, explanation: 'm = nM = 2·44.01 = 88.02 g.', rule: 'Масса m = nM.', example: '1 mol CO₂ имеет массу около 44.01 g.', hint: 'Сначала найди M(CO₂).', tags: ['moles', 'mass', 'carbon-dioxide'], parameters: { compound: 'CO2', scaleMode: 'moles-to-mass', sampleMoles: 2, molarMass: 44.01 } }),
  makeTask(89, { topic: 'Количество вещества', subtopic: 'Моли в массу', difficulty: 1, station: 'solution-laboratory', interactionType: 'virtual-scales', prompt: 'Найди массу 0.25 mol NaCl в граммах.', correctAnswer: { value: 14.61, absoluteTolerance: 0.1, unit: 'g' }, explanation: 'm = 0.25·58.44 = 14.61 g.', rule: 'Масса m = nM.', example: '0.50 mol NaCl имеет массу 29.22 g.', hint: 'Умножь 0.25 mol на 58.44 g/mol.', tags: ['moles', 'mass', 'sodium-chloride'], parameters: { compound: 'NaCl', scaleMode: 'moles-to-mass', sampleMoles: 0.25, molarMass: 58.44 } }),
  makeTask(90, { topic: 'Количество вещества', subtopic: 'Моли в массу', difficulty: 1, station: 'solution-laboratory', interactionType: 'virtual-scales', prompt: 'Найди массу 0.10 mol CaCO₃ в граммах.', correctAnswer: { value: 10.01, absoluteTolerance: 0.1, unit: 'g' }, explanation: 'm = 0.10·100.09 ≈ 10.01 g.', rule: 'Масса m = nM.', example: '1 mol CaCO₃ имеет массу 100.09 g.', hint: 'Умножь количество вещества на молярную массу.', tags: ['moles', 'mass', 'carbonate', 'construction'], parameters: { compound: 'CaCO3', scaleMode: 'moles-to-mass', sampleMoles: 0.10, molarMass: 100.09 } }),
  makeTask(91, { topic: 'Растворы', subtopic: 'Молярная концентрация', difficulty: 1, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: '0.5 mol вещества находится в 1 L раствора. Найди C в mol/L.', correctAnswer: { value: 0.5, absoluteTolerance: 0.01, unit: 'mol/L' }, explanation: 'C = n/V = 0.5/1 = 0.5 mol/L.', rule: concentrationRule, example: '1 mol в 2 L даёт 0.5 mol/L.', hint: numericHint, tags: ['molarity', 'solution'] }),
  makeTask(92, { topic: 'Растворы', subtopic: 'Молярная концентрация', difficulty: 1, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: '0.2 mol вещества находится в 500 mL раствора. Найди C в mol/L.', correctAnswer: { value: 0.4, absoluteTolerance: 0.01, unit: 'mol/L' }, explanation: '500 mL = 0.500 L; C = 0.2/0.500 = 0.4 mol/L.', rule: concentrationRule, example: '0.1 mol в 0.25 L также даёт 0.4 mol/L.', hint: 'Переведи 500 mL в 0.500 L.', tags: ['molarity', 'volume'] }),
  makeTask(93, { topic: 'Растворы', subtopic: 'Количество вещества в растворе', difficulty: 1, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: 'Раствор имеет C = 2 mol/L и V = 0.25 L. Найди n.', correctAnswer: { value: 0.5, absoluteTolerance: 0.01, unit: 'mol' }, explanation: 'n = CV = 2·0.25 = 0.5 mol.', rule: 'Количество вещества в растворе n = CV.', example: '1 mol/L · 0.5 L = 0.5 mol.', hint: numericHint, tags: ['molarity', 'moles'] }),
  makeTask(94, { topic: 'Растворы', subtopic: 'Объём раствора', difficulty: 1, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: 'Какой объём раствора C = 1 mol/L содержит 0.5 mol вещества?', correctAnswer: { value: 0.5, absoluteTolerance: 0.01, unit: 'L' }, explanation: 'V = n/C = 0.5/1 = 0.5 L.', rule: 'Из C = n/V следует V = n/C.', example: '0.25 mol при 1 mol/L занимает 0.25 L.', hint: numericHint, tags: ['molarity', 'volume'] }),
  makeTask(95, { topic: 'Приготовление растворов', subtopic: 'Навеска соли', difficulty: 2, station: 'solution-laboratory', interactionType: 'solution-preparation', prompt: 'Какую массу NaCl взять для 500 mL раствора 0.20 mol/L?', correctAnswer: { value: 5.84, absoluteTolerance: 0.05, unit: 'g' }, explanation: 'n = 0.20·0.500 = 0.100 mol; m = 0.100·58.44 = 5.844 g.', rule: 'Для навески используй m = CVM.', example: 'Раствор готовят виртуально с доведением до конечного объёма.', hint: '1000 mL соответствуют 1 L.', tags: ['solution-preparation', 'molarity', 'sodium-chloride'], parameters: { compound: 'NaCl', solutionMode: 'mass', targetVolumeMl: 500, targetConcentration: 0.20, molarMass: 58.44, solutionVolumeChoicesL: [5.000, 0.500, 0.050] } }),
  makeTask(96, { topic: 'Приготовление растворов', subtopic: 'Навеска щёлочи', difficulty: 2, station: 'solution-laboratory', interactionType: 'solution-preparation', prompt: 'Какую массу NaOH взять для 250 mL раствора 0.10 mol/L?', correctAnswer: { value: 1, absoluteTolerance: 0.03, unit: 'g' }, explanation: 'n = 0.10·0.250 = 0.025 mol; m = 0.025·40.00 = 1.00 g.', rule: 'Для навески используй m = CVM.', example: 'Все операции в ChemSite являются виртуальными.', hint: '1000 mL соответствуют 1 L; молярная масса указана на панели.', tags: ['solution-preparation', 'molarity', 'sodium-hydroxide'], parameters: { compound: 'NaOH', solutionMode: 'mass', targetVolumeMl: 250, targetConcentration: 0.10, molarMass: 40.00, solutionVolumeChoicesL: [0.025, 2.500, 0.250] } }),
  makeTask(97, { topic: 'Растворы', subtopic: 'Разбавление', difficulty: 2, station: 'solution-laboratory', interactionType: 'solution-preparation', prompt: 'Из 1.0 mol/L раствора нужно получить 500 mL раствора 0.20 mol/L. Какой объём исходного раствора взять?', correctAnswer: { value: 100, absoluteTolerance: 1, unit: 'mL' }, explanation: 'V₁ = C₂V₂/C₁ = 0.20·500/1.0 = 100 mL.', rule: 'При разбавлении C₁V₁ = C₂V₂.', example: 'Остальной объём до 500 mL восполняет растворитель.', hint: 'Количество растворённого вещества при разбавлении сохраняется.', tags: ['dilution', 'volume'], parameters: { solutionMode: 'dilution', targetVolumeMl: 500, targetConcentration: 0.20, stockConcentration: 1.0, solutionVolumeChoicesL: [0.500, 0.050, 5.000] } }),
  makeTask(98, { topic: 'Растворы', subtopic: 'Разбавление', difficulty: 2, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: '50 mL раствора 2 mol/L довели до 200 mL. Найди новую концентрацию.', correctAnswer: { value: 0.5, absoluteTolerance: 0.01, unit: 'mol/L' }, explanation: 'C₂ = C₁V₁/V₂ = 2·50/200 = 0.5 mol/L.', rule: 'При разбавлении количество растворённого вещества сохраняется.', example: 'Увеличение объёма в 4 раза уменьшает C в 4 раза.', hint: 'Используй C₁V₁ = C₂V₂.', tags: ['dilution', 'molarity'] }),
  makeTask(99, { topic: 'Растворы', subtopic: 'Массовая доля', difficulty: 1, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: '10 g соли растворили в 90 g воды. Найди массовую долю соли в процентах.', correctAnswer: { value: 10, absoluteTolerance: 0.1, unit: '%' }, explanation: 'Масса раствора 100 g; w = 10/100·100% = 10%.', rule: 'w = m(вещества)/m(раствора)·100%.', example: '5 g в 95 g воды также дают 5%.', hint: 'Сначала сложи массы соли и воды.', tags: ['mass-fraction', 'solution'] }),
  makeTask(100, { topic: 'Растворы', subtopic: 'Массовая доля', difficulty: 1, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: 'В 200 g раствора содержится 25 g вещества. Найди массовую долю в процентах.', correctAnswer: { value: 12.5, absoluteTolerance: 0.1, unit: '%' }, explanation: 'w = 25/200·100% = 12.5%.', rule: 'w = m(вещества)/m(раствора)·100%.', example: '20 g в 200 g раствора дают 10%.', hint: numericHint, tags: ['mass-fraction', 'solution'] }),
  makeTask(101, { topic: 'Кислотность', subtopic: 'Шкала pH', difficulty: 1, station: 'solution-laboratory', interactionType: 'pH-terminal', prompt: 'Измерь pH образца A. Какая среда?', correctAnswer: 'кислая', options: ['кислая', 'нейтральная', 'щелочная'], explanation: 'pH ниже 7 соответствует кислой среде в стандартной учебной модели.', rule: 'pH < 7 — кислая среда.', example: 'pH 2 также соответствует кислой среде.', hint: 'Сравни pH с 7.', tags: ['pH', 'acidic'], parameters: { phSamples: [{ label: 'ОБРАЗЕЦ A', value: 3 }] } }),
  makeTask(102, { topic: 'Кислотность', subtopic: 'Шкала pH', difficulty: 1, station: 'solution-laboratory', interactionType: 'pH-terminal', prompt: 'Измерь pH образца B при 25 °C. Какая среда?', correctAnswer: 'нейтральная', options: ['нейтральная', 'кислая', 'щелочная'], explanation: 'В базовой модели pH 7 соответствует нейтральной среде.', rule: 'При 25 °C нейтральный водный раствор имеет pH около 7.', example: 'Чистая вода в учебной модели нейтральна.', hint: 'Это центральное значение учебной шкалы.', tags: ['pH', 'neutral'], parameters: { phSamples: [{ label: 'ОБРАЗЕЦ B', value: 7 }] } }),
  makeTask(103, { topic: 'Кислотность', subtopic: 'Шкала pH', difficulty: 1, station: 'solution-laboratory', interactionType: 'pH-terminal', prompt: 'Измерь pH образца C. Какая среда?', correctAnswer: 'щелочная', acceptedAnswers: ['основная'], options: ['щелочная', 'нейтральная', 'кислая'], explanation: 'pH выше 7 соответствует щелочной среде в стандартной учебной модели.', rule: 'pH > 7 — щелочная среда.', example: 'pH 12 также соответствует щелочной среде.', hint: 'Сравни pH с 7.', tags: ['pH', 'basic'], parameters: { phSamples: [{ label: 'ОБРАЗЕЦ C', value: 11 }] } }),
  makeTask(104, { topic: 'Кислотность', subtopic: 'Расчёт pH', difficulty: 2, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: 'В учебном приближении для разбавленного раствора [H⁺] = 10⁻⁴ mol/L. Найди pH.', correctAnswer: { value: 4, absoluteTolerance: 0.01 }, explanation: 'pH = −lg[H⁺] = −lg(10⁻⁴) = 4.', rule: 'Для разбавленного раствора в учебном приближении pH ≈ −lg[H⁺].', example: '[H⁺] = 10⁻³ mol/L даёт pH 3.', hint: 'Знак показателя степени меняется при вычислении −lg.', tags: ['pH', 'hydrogen-ion'] }),
  makeTask(105, { topic: 'Кислотность', subtopic: 'Расчёт pH', difficulty: 2, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: 'В учебном приближении [H⁺] = 10⁻² mol/L. Найди pH.', correctAnswer: { value: 2, absoluteTolerance: 0.01 }, explanation: 'pH = −lg(10⁻²) = 2, поэтому раствор кислый.', rule: 'Для разбавленного раствора в учебном приближении pH ≈ −lg[H⁺].', example: '[H⁺] = 10⁻⁵ mol/L даёт pH 5.', hint: 'Возьми отрицательный десятичный логарифм.', tags: ['pH', 'hydrogen-ion'] }),
  makeTask(106, { topic: 'Кислотность', subtopic: 'Концентрация H⁺', difficulty: 2, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: 'В учебном приближении pH = 5. Найди [H⁺] в mol/L.', correctAnswer: { value: 0.00001, relativeTolerance: 0.01, unit: 'mol/L' }, explanation: '[H⁺] = 10⁻ᵖᴴ = 10⁻⁵ mol/L.', rule: 'Для разбавленного раствора в учебном приближении [H⁺] ≈ 10⁻ᵖᴴ.', example: 'При pH 3 концентрация H⁺ равна 10⁻³ mol/L.', hint: 'Возведи 10 в степень −pH.', tags: ['pH', 'hydrogen-ion'] }),
  makeTask(107, { topic: 'Кислотность', subtopic: 'Сравнение pH', difficulty: 1, station: 'solution-laboratory', interactionType: 'pH-terminal', prompt: 'Измерь оба образца. Какой раствор более кислый?', correctAnswer: 'образец A', options: ['образец A', 'образец B', 'одинаково'], explanation: 'Образец A имеет pH 2, образец B — pH 4. Меньшее pH соответствует большей концентрации H⁺.', rule: 'Шкала pH логарифмическая и обратна концентрации H⁺.', example: 'pH 3 кислее pH 5.', hint: 'Более кислый раствор имеет меньшее pH.', tags: ['pH', 'comparison'], parameters: { phSamples: [{ label: 'ОБРАЗЕЦ A', value: 2 }, { label: 'ОБРАЗЕЦ B', value: 4 }] } }),
  makeTask(108, { topic: 'Кислотность', subtopic: 'Логарифмическая шкала', difficulty: 2, station: 'solution-laboratory', interactionType: 'numeric-calculation', prompt: 'В учебном приближении во сколько раз [H⁺] при pH 3 выше, чем при pH 5?', correctAnswer: { value: 100, absoluteTolerance: 0.1, unit: 'раз' }, explanation: 'Разница в 2 единицы pH означает отношение 10² = 100.', rule: 'В учебном приближении одна единица pH соответствует десятикратному изменению [H⁺].', example: 'Разница в 3 единицы даёт 1000 раз.', hint: 'Возведи 10 в степень разности pH.', tags: ['pH', 'comparison'] }),
  makeTask(109, { topic: 'Электролиты', subtopic: 'Диссоциация солей', difficulty: 1, station: 'ionic-reaction-station', interactionType: 'dissociation', prompt: 'Напиши диссоциацию NaCl в воде.', correctAnswer: 'NaCl -> Na+ + Cl-', explanation: 'Растворимый NaCl распадается на Na⁺ и Cl⁻.', rule: 'Индексы и заряды определяют число и заряд ионов.', example: 'KCl → K⁺ + Cl⁻.', hint: 'Получаются два однозарядных иона.', tags: ['dissociation', 'salt'], parameters: { compound: 'NaCl' } }),
  makeTask(110, { topic: 'Электролиты', subtopic: 'Диссоциация солей', difficulty: 1, station: 'ionic-reaction-station', interactionType: 'dissociation', prompt: 'Напиши диссоциацию CaCl₂ в воде.', correctAnswer: 'CaCl2 -> Ca^2+ + 2Cl-', explanation: 'Одна формульная единица CaCl₂ даёт Ca²⁺ и два Cl⁻.', rule: 'Коэффициент перед ионом соответствует индексу в формуле соли.', example: 'MgCl₂ → Mg²⁺ + 2Cl⁻.', hint: 'Учти два хлорид-иона.', tags: ['dissociation', 'salt', 'calcium'], parameters: { compound: 'CaCl2' } }),
  makeTask(111, { topic: 'Электролиты', subtopic: 'Диссоциация солей', difficulty: 1, station: 'ionic-reaction-station', interactionType: 'dissociation', prompt: 'Напиши диссоциацию Na₂SO₄ в воде.', correctAnswer: 'Na2SO4 -> 2Na+ + SO4^2-', explanation: 'Na₂SO₄ даёт два Na⁺ и один SO₄²⁻.', rule: 'Суммарный заряд продуктов диссоциации равен нулю.', example: 'K₂SO₄ → 2K⁺ + SO₄²⁻.', hint: 'Индекс 2 перед Na превращается в коэффициент.', tags: ['dissociation', 'salt', 'sulfate'], parameters: { compound: 'Na2SO4' } }),
  makeTask(112, { topic: 'Электролиты', subtopic: 'Диссоциация солей', difficulty: 2, station: 'ionic-reaction-station', interactionType: 'dissociation', prompt: 'Напиши диссоциацию AlCl₃ в воде.', correctAnswer: 'AlCl3 -> Al^3+ + 3Cl-', explanation: 'AlCl₃ даёт Al³⁺ и три Cl⁻.', rule: 'Число и заряд ионов должны сохранять электронейтральность.', example: 'FeCl₃ → Fe³⁺ + 3Cl⁻.', hint: 'К одному Al³⁺ нужны три хлорид-иона.', tags: ['dissociation', 'salt', 'aluminium'], parameters: { compound: 'AlCl3' } }),
  makeTask(113, { topic: 'Электролиты', subtopic: 'Сильные электролиты', difficulty: 1, station: 'ionic-reaction-station', interactionType: 'classification', prompt: 'Просканируй водную модель HCl. К какому типу электролитов относится вещество?', correctAnswer: 'сильный электролит', options: ['сильный электролит', 'слабый электролит', 'неэлектролит'], explanation: 'HCl в разбавленном водном растворе практически полностью диссоциирует.', rule: 'Сильные кислоты относятся к сильным электролитам.', example: 'HNO₃ — сильный электролит.', hint: 'Оцени, какая доля частиц присутствует в виде ионов.', tags: ['electrolyte', 'strong', 'acid'], parameters: { compound: 'HCl', ionizationSamples: [{ label: 'HCl', observation: 'Почти все растворённые частицы представлены ионами.' }] } }),
  makeTask(114, { topic: 'Электролиты', subtopic: 'Сильные электролиты', difficulty: 1, station: 'ionic-reaction-station', interactionType: 'classification', prompt: 'Просканируй водную модель NaOH. К какому типу электролитов относится вещество?', correctAnswer: 'сильный электролит', options: ['сильный электролит', 'слабый электролит', 'неэлектролит'], explanation: 'Растворимый NaOH практически полностью распадается на Na⁺ и OH⁻.', rule: 'Растворимые щёлочи являются сильными электролитами.', example: 'KOH — сильный электролит.', hint: 'Оцени, какая доля частиц присутствует в виде ионов.', tags: ['electrolyte', 'strong', 'base'], parameters: { compound: 'NaOH', ionizationSamples: [{ label: 'NaOH', observation: 'Почти все растворённые частицы представлены ионами.' }] } }),
  makeTask(115, { topic: 'Электролиты', subtopic: 'Слабые электролиты', difficulty: 1, station: 'ionic-reaction-station', interactionType: 'classification', prompt: 'Просканируй водную модель уксусной кислоты. К какому типу электролитов она относится?', correctAnswer: 'слабый электролит', options: ['слабый электролит', 'сильный электролит', 'неэлектролит'], explanation: 'Уксусная кислота диссоциирует в воде лишь частично.', rule: 'Слабые кислоты являются слабыми электролитами.', example: 'CH₃COOH ⇌ H⁺ + CH₃COO⁻.', hint: 'Сопоставь количество ионов и недиссоциированных молекул.', tags: ['electrolyte', 'weak', 'acid'], parameters: { compound: 'CH3COOH', ionizationSamples: [{ label: 'CH₃COOH', observation: 'Преобладают молекулы; небольшая доля частиц представлена ионами.' }] } }),
  makeTask(116, { topic: 'Электролиты', subtopic: 'Неэлектролиты', difficulty: 1, station: 'ionic-reaction-station', interactionType: 'classification', prompt: 'Просканируй четыре водные модели. Какое вещество является неэлектролитом?', correctAnswer: 'сахароза', options: ['сахароза', 'NaCl', 'HCl', 'NaOH'], explanation: 'Сахароза растворяется молекулярно и практически не образует ионов.', rule: 'Неэлектролиты не дают заметного количества подвижных ионов в растворе.', example: 'Раствор глюкозы также является неэлектролитом.', hint: 'Ищи образец, в котором практически нет ионов растворённого вещества.', tags: ['electrolyte', 'nonelectrolyte'], parameters: { ionizationSamples: [{ label: 'сахароза', observation: 'Частицы растворённого вещества остаются молекулами; его ионы практически отсутствуют.' }, { label: 'NaCl', observation: 'Растворённое вещество представлено преимущественно ионами Na⁺ и Cl⁻.' }, { label: 'HCl', observation: 'Растворённое вещество представлено преимущественно ионами H⁺ и Cl⁻.' }, { label: 'NaOH', observation: 'Растворённое вещество представлено преимущественно ионами Na⁺ и OH⁻.' }] } }),
  makeTask(117, { topic: 'Гидролиз', subtopic: 'Соль сильной кислоты и основания', difficulty: 1, station: 'ionic-reaction-station', interactionType: 'hydrolysis', prompt: 'Происходит ли значимый гидролиз NaCl в базовой учебной модели?', correctAnswer: 'практически нет', acceptedAnswers: ['нет'], options: ['практически нет', 'да, по катиону', 'да, по аниону'], explanation: 'NaCl образован сильной кислотой HCl и сильным основанием NaOH.', rule: 'Ионы соли сильной кислоты и сильного основания практически не гидролизуются.', example: 'Раствор KNO₃ также близок к нейтральному.', hint: 'Оцени силу исходных кислоты и основания.', tags: ['hydrolysis', 'neutral-salt'], parameters: { compound: 'NaCl', comparisonRuns: [{ setting: 'Анион Cl⁻', observation: 'Cl⁻ — сопряжённое основание сильной кислоты HCl; в учебной модели значимый гидролиз отсутствует.' }, { setting: 'Катион Na⁺', observation: 'Na⁺ происходит от сильного основания NaOH; в учебной модели значимый гидролиз отсутствует.' }] } }),
  makeTask(118, { topic: 'Гидролиз', subtopic: 'Карбонаты', difficulty: 2, station: 'ionic-reaction-station', interactionType: 'hydrolysis', prompt: 'Какая среда характерна для раствора Na₂CO₃?', correctAnswer: 'щелочная', acceptedAnswers: ['основная'], options: ['щелочная', 'кислая', 'нейтральная'], explanation: 'CO₃²⁻ гидролизуется с образованием OH⁻, поэтому среда щелочная.', rule: 'Анион слабой кислоты может создавать щелочную среду.', example: 'CO₃²⁻ + H₂O ⇌ HCO₃⁻ + OH⁻.', hint: 'Карбонат-ион — остаток слабой угольной кислоты.', tags: ['hydrolysis', 'basic', 'carbonate'], parameters: { compound: 'Na2CO3', comparisonRuns: [{ setting: 'Анион CO₃²⁻', observation: 'CO₃²⁻ — остаток слабой H₂CO₃; с водой образует HCO₃⁻ и OH⁻.' }, { setting: 'Катион Na⁺', observation: 'Na⁺ происходит от сильного основания NaOH; значимого гидролиза катиона нет.' }] } }),
  makeTask(119, { topic: 'Гидролиз', subtopic: 'Соли аммония', difficulty: 2, station: 'ionic-reaction-station', interactionType: 'hydrolysis', prompt: 'Какая среда характерна для раствора NH₄Cl?', correctAnswer: 'кислая', options: ['кислая', 'щелочная', 'нейтральная'], explanation: 'NH₄⁺ гидролизуется с образованием H₃O⁺, поэтому среда кислая.', rule: 'Катион слабого основания может создавать кислую среду.', example: 'NH₄⁺ + H₂O ⇌ NH₃ + H₃O⁺.', hint: 'NH₄⁺ связан со слабым основанием NH₃·H₂O.', tags: ['hydrolysis', 'acidic', 'ammonium'], parameters: { compound: 'NH4Cl', comparisonRuns: [{ setting: 'Анион Cl⁻', observation: 'Cl⁻ происходит от сильной кислоты HCl; значимого гидролиза аниона нет.' }, { setting: 'Катион NH₄⁺', observation: 'NH₄⁺ — сопряжённая кислота слабого основания NH₃; с водой образует H₃O⁺.' }] } }),
  makeTask(120, { topic: 'Анализ растворов', subtopic: 'Лабораторная миссия', difficulty: 3, station: 'inspection-station', interactionType: 'construction-mission', prompt: 'Изучи показания неизвестного раствора и определи вещество.', correctAnswer: 'NaCl', acceptedAnswers: ['хлорид натрия'], options: ['NaCl', 'Na₂CO₃', 'NH₄Cl', 'AgNO₃'], explanation: 'Набор ионов Na⁺ и Cl⁻ однозначно соответствует NaCl; его раствор близок к нейтральному.', rule: 'Идентификацию проводят по совокупности pH, ионного состава и проверенных реакций.', example: 'NaCl → Na⁺ + Cl⁻.', hint: 'Собери нейтральную соль из обнаруженных ионов.', tags: ['mission', 'solution-analysis', 'ions'], parameters: { compound: 'NaCl', missionSteps: [{ title: 'pH-метр', readout: 'В учебной модели pH ≈ 7.' }, { title: 'Ионный сканер', readout: 'Обнаружены Na⁺ и Cl⁻.' }, { title: 'Контрольные пробы', readout: 'В заданных пробах осадок не образуется.' }] } }),
] as const
